### ISSUE TITLE
ZMQ_HAVE_CURVE not defined

### ISSUE THREAD

**Issue by gitpupillo** [zeromq/libzmq#1963] opened 2016-05-05 15:58 UTC
I've built successfully libzmq under VS2012.  However ZMQ_HAVE_CURVE is not defined and I can't use curve encryption.
Please tell me where I was wrong
Thanks
Asi

**Comment by hitstergtd** [comment] 2016-05-05 16:08
Asi, did you build using CMake or straight from the Solution file?

**Comment by gitpupillo** [comment] 2016-05-05 16:24
No I did exactly what shown here: http://zeromq.org/build:_start
Note: I had to add inttypes.h

**Comment by amonamarth** [comment] 2016-05-09 07:34
I second that :)
I built libzmq with VS2015 (builds/msvc/vs2015) using `buildall.bat` in a VS command prompt. I think the problem is that configure.bat does not set the right preprocessor definition in platform.hpp; currently it sets `HAVE_LIBSODIUM`, but in the code `ZMQ_HAVE_CURVE` is the preprocessor definition that is checked. As I have understood it, libsodium is only used for the curve encryption part of libzmq?

Also, I noticed that even when setting `ZMQ_HAVE_CURVE` manually, the dynamic build will not work since there are missing symbols (any call to libsodium). I had to add `libsodium.lib`, i.e. _not_ the static library, but the import library located in the same folder as the `libsodium.dll`. I'm not sure if this is the right way to do it, but it worked for me at least :) 
Correct me if I'm wrong, but if I understand correctly the only other alternatives to not link with the import library would be to either link to the regular `libsodium.lib` or define function stubs and load `libsodium.dll` manually at runtime using [`LoadLibrary`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175%28v=vs.85%29.aspx) (for the DLL) and [`GetProcAdress`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683212%28v=vs.85%29.aspx) for the function handles?

**Comment by hitstergtd** [comment] 2016-05-09 12:11
Hmm. Anything that libsodium is used for should be possible with the built-in tweetnacl library so not sure why it's fixated on Sodium.

**Comment by evoskuil** [comment] 2016-05-13 18:48
This should be resolved by #1988

**Comment by hitstergtd** [comment] 2016-05-13 21:37
Please let us know so that we can close the issue.

**Comment by gitpupillo** [comment] 2016-05-16 14:13
I tried to build via CMake and it works.
Instead, via buildall etc..., if libsodium is used, I had to modify configure.bat adding 
ECHO #define ZMQ_HAVE_CURVE>> platform.hpp	
If libsodium is not used, it doesn't work. I think that in this case I should modify the visual studio project files in order to include the tweetnacl source files.
I didn't tried however

**Comment by evoskuil** [comment] 2016-05-17 01:54
@gitpupillo The Visual Studio user interface includes the option to enable libsodium (and tweetnacl). If either of these is enabled ZMQ_HAVE_CURVE is automatically defined.

![image](https://cloud.githubusercontent.com/assets/1369335/15308955/4aeb7294-1b97-11e6-8031-5652928920a2.png)

If you change the setting in the UI and then build you will get the expected result.

**Comment by gitpupillo** [comment] 2016-05-17 07:22
In my libzmq property page, only openpgm and gssapi are present.I'm using
VS2012 express.


2016-05-17 3:54 GMT+02:00 Eric Voskuil <notifications@github.com>:

**Comment by evoskuil** [comment] 2016-05-17 08:03
This is a screen shot from VS2012 of the vs2012 project:

![image](https://cloud.githubusercontent.com/assets/1369335/15315206/007d310a-1bcb-11e6-96e5-6771ae64af00.png)

I know, they look exactly the same, but this is 2012.

**Comment by evoskuil** [comment] 2016-05-17 08:05
Do you have libsodium installed in a sibling directory?

**Comment by gitpupillo** [comment] 2016-05-17 08:42
Yes, libsodium folder is at the same level of libzmq folder.
In ..\vs2012\libzmq.xml file, I see references to openpgm and gssapi only.
I must have done something wrong if at you everything is ok



2016-05-17 10:05 GMT+02:00 Eric Voskuil <notifications@github.com>:

**Comment by rgbkrk** [comment] 2016-05-17 12:59
Is there a good way to build these on Windows using visual studio command line tools?

**Comment by evoskuil** [comment] 2016-05-18 01:19
@rgbkrk See: https://github.com/zeromq/libzmq/blob/master/builds/msvc/readme.txt

**Comment by evoskuil** [comment] 2016-05-18 01:20
@gitpupillo I think your sources are not current.

**Comment by gitpupillo** [comment] 2016-05-18 07:50
Hi,
I cloned again the git (git clone https://github.com/zeromq/libzmq.git)  and
now I can see all these options but there is no more configure.bat in
libzmq\builds\msvc.
So I can't follow the procedure shown in http://zeromq.org/build:_start (
something changed in the git since 5 of May I guess ).



2016-05-18 3:20 GMT+02:00 Eric Voskuil <notifications@github.com>:

**Comment by evoskuil** [comment] 2016-05-18 07:58
Yeah, just skip the `configure.bat` step and run `build.bat` in place of `buildall.bat`.

**Comment by evoskuil** [comment] 2016-05-18 08:11
I updated the instructions page: http://zeromq.org/build:_start

**Comment by gitpupillo** [comment] 2016-05-18 11:01
I saw; I tried the new instructions.
I get this error both using build.bat or vs2012 solution:
Error 1 error LNK2019: unresolved external symbol "public: __thiscall
zmq::dgram_t::dgram_t(class zmq::ctx_t *,unsigned int,int)" (??0dgram_t@zmq
@@QAE@PAVctx_t@1@IH@Z) referenced in function "public: static class
zmq::socket_base_t * __cdecl zmq::socket_base_t::create(int,class
zmq::ctx_t *,unsigned int,int)" (?create@socket_base_t@zmq@
@SAPAV12@HPAVctx_t@2@IH@Z)
C:\Temp\mylibzmq\libzmq\builds\msvc\vs2012\libzmq\socket_base.obj libzmq


2016-05-18 10:11 GMT+02:00 Eric Voskuil <notifications@github.com>:

**Comment by evoskuil** [comment] 2016-05-18 19:28
This is a new error due to a missing file in the VS projects. I've resolved it here: https://github.com/zeromq/libzmq/pull/2001

**Comment by gitpupillo** [comment] 2016-05-19 09:05
Now it works as expected (I only tried vs2012 solution however).
Thanks!

2016-05-18 21:29 GMT+02:00 Eric Voskuil <notifications@github.com>:

**Comment by evoskuil** [comment] 2016-05-19 20:16
@gitpupillo Feel free to close this now that it's working.

**Comment by ahmetkakici** [comment] 2016-05-24 11:49
I've just updated my repo and noticed that configure.bat has gone.
When i try to open libzmq.sln with vs2013 and set libsodium on from property pages, it builds with libsodium support (checking it with dependency walker)
But i have to build libzmq with teamcity and don't know how to set libsodium support, i'm just calling bulidbase.bat with parameters; soltuion file and "12" as visual studio version.

So i cannot find how to build libzmq with libsodium support without using visual studio's property pages.

Btw, libzmq and libsodium folders are in the same folder.

**Comment by evoskuil** [comment] 2016-05-24 18:33
Hi @ahmetkakici, scroll up on this page and see the Visual Studio property pages.

**Comment by ahmetkakici** [comment] 2016-05-25 06:16
Hello @evoskuil 
I can enable libsodium from property pages but i'm using a continuous integration tool for building libzmq & libsodium. So i'm not opening visual studio to set that values, i'm just executing buildBase.bat file from command line, confiugre.bat was handling this situation and defining HAVE_SODIUM variable but now i cannot do that.

**Comment by evoskuil** [comment] 2016-05-25 06:56
The use of a batch file to edit a source-embedded symbol (as before) overrides (breaks) the options as exposed in the user interface. Also the detection in the batch file required one to *uninstall* libsodium to build without the option. Finally, this method was not applied to the several other options and doing so would have created significantly complex to implement and therefore fragile batch file-based configuration.

The primary reasons to have VS builds are discovery of options and code in the user interface, and the visual debugger. For these reasons the behavior was reverted to relying native VS configuration. See discussion here: https://github.com/zeromq/libzmq/issues/1985 . The proper way to do this is to set property values via msbuild.

`Option-sodium` is the value that must be affected (from libzmq.props):
```xml
  <ItemDefinitionGroup>
    <ClCompile>
...
      <PreprocessorDefinitions Condition="'$(Option-sodium)' == 'true'">ZMQ_USE_LIBSODIUM;%(PreprocessorDefinitions)</PreprocessorDefinitions>
...
    </ClCompile>
...
  </ItemDefinitionGroup>
```
`Option-sodium` is exposed in the property pages by (in libzmq.xml):
```xml
<?xml version="1.0" encoding="utf-8"?>
<ProjectSchemaDefinitions xmlns="clr-namespace:Microsoft.Build.Framework.XamlTypes;assembly=Microsoft.Build.Framework">
  <Rule Name="libzmq-uiextension" PageTemplate="tool" DisplayName="ZMQ Options" SwitchPrefix="/" Order="1">
...
    <EnumProperty Name="Option-sodium" DisplayName="Enable Sodium" Description="Enable Sodium build option" Category="sodium">
      <EnumValue Name="" DisplayName="No" />
      <EnumValue Name="true" DisplayName="Yes" />
    </EnumProperty>
...
  </Rule>
</ProjectSchemaDefinitions>
```
I believe the command line option would be:
```
msbuild.exe MyProj.proj /p:Option-sodium=true
```
However I have not tested this myself.

**Comment by ahmetkakici** [comment] 2016-05-25 10:47
@evoskuil thanks for information. I've already read #1985 and got your point but just curious about that if there is a new way to do this instead of using configure.bat mechanism. Now i see that i've to configure libzmq.xml.

Thank you again for your detailed reply.

**Comment by evoskuil** [comment] 2016-05-25 11:25
@ahmetkakici NP. The imported properties and xml are shared from the VS2015 folder to minimize duplication across versions. These are in fact pulled into the VS2013 (and other) builds.

**Comment by ahmetkakici** [comment] 2016-05-25 13:05
@evoskuil instead of using buildbase.bat I've built solution with; 
`msubild.exe /p:Option-sodium=true libzmq.sln`
in vs2013 folder.

It worked, thanks again.

**Comment by evoskuil** [comment] 2016-05-25 20:48
@ahmetkakici Great, thanks for letting us know.

**Comment by Allidylls** [comment] 2016-08-19 06:22
Yes, I have the same error of zeromq-4.1.5.zip when build with MSVC 2010 on Windows 10.
ZMQ_HAVE_CURVE is not defined and there is no ./builds/msvc/configure.bat file as described in http://zeromq.org/build:encryption

**Comment by bluca** [comment] 2017-01-03 15:48
Closing as it was reported fixed

**Closed by bluca** 2017-01-03 15:48 UTC
Labels: Build Problem, Platform (windows/msvc)

**Comment by jay11ca39** [comment] 2018-09-03 17:42
Hi @ahmetkakici and @evoskuil 
I have one query regarding windows build. I am using the msbuild for v2015:

```
$ cd builds/msvc/vs2015
$ MSBuild libzmq.sln /p:Configuration=StaticRelease,Option-sodium=true
```

I am getting the error related to **headers of "Sodium library"** .
```
libzmq\src\curve_server.hpp(38): fatal error C1083: Cannot open include file: 'sodium.h': No such file or directory (compiling source file ..\..\..\..\src\curve_server.cpp) [libzmq\builds\msvc\vs2015\libzmq\libzmq.vcxproj]
  ..\..\..\..\src\ctx.cpp(52): fatal error C1083: Cannot open include file: 'sodium.h': No such file or directory [libzmq\builds\msvc\vs2015\libzmq\libzmq.vcxproj]
```
**Do you have any idea where should I place the libsodium library in libzmq?** and how to build the .dll/ .lib of libsodium in libzmq folder, so it can link while building using MSBuild .... 
Thanks in advance.
