### ISSUE TITLE
Robust context termination

### ISSUE THREAD

**Issue by dkrikun** [zeromq/libzmq#1377] opened 2015-04-20 10:28 UTC
`WSASTARTUP not yet performed` assertion failure is a disturbing problem that might arise due to (esoteric)  reasons. To ease libzmq usage, it could we:

1. Perform context termination gracefully even if wsa has been shut down.

2. If that is not possible, at least do not assert.

**Comment by dkrikun** [comment] 2015-04-20 10:29
See also:https://github.com/zeromq/czmq/issues/989

**Comment by hintjens** [comment] 2015-04-20 10:55
Duplicate of #1144 

Fixed with patch: https://github.com/zeromq/libzmq/pull/1341

If someone could test and confirm, then I'll backport this patch to 4.x and 3.x.

**Closed** 2015-04-20 11:28 UTC

**Comment by dkrikun** [comment] 2015-04-21 14:25
I do not have the master in my environment, but the patch worked for me too.

**Comment by hintjens** [comment] 2015-04-21 16:50
Great, thanks. :)
