### ISSUE TITLE
Server with ZMQ_DEALER socket receiving wrong messages

### ISSUE THREAD

**Issue by Prachi2807** [zeromq/libzmq#2115] opened 2016-09-20 10:52 UTC
Hi,
Ideal Scenario:
If client comes up  before server , then the messages will be buffered.
and after the server comes up , those buffered messages will be  received by server.
Problem:
The server is receiving only the last message from the client
For Ex :
client Side 
> ./dealer1
Enter the Message :SEND
,Size of message sent :4
Enter the Message :BEFORE
,Size of message sent :6
Enter the Message :SERVER
,Size of message sent :6
Enter the Message :

After server comes up , it will receive the following messages-
 ./dealer2
Bind Successfull
Buff Received is :SERV
Buff Received is :SERV
Buff Received is :SERVER

Can you please tell why the sever is receiving only last messages.

**Comment by bluca** [comment] 2016-09-20 12:26
Could you please share the code that causes the issue? Ideally in the format of the existing test cases in tests/test_*.cpp so that if it's a bug we can reproduce and fix it

**Comment by Prachi2807** [comment] 2016-09-20 13:54
**client.cpp**
_void *ctx=zmq_ctx_new();
 void *sockDealer2=zmq_socket(ctx,ZMQ_DEALER);
 int rc=zmq_connect(sockDealer2,"tcp://localhost:6611");
 if(rc!=0)
 {
 std::cout<<"Error in zmq_connect() :"<<zmq_strerror (errno);
 }
 else
 {
  while(1)
  {
  zmq_msg_t msg;
  std::string buff;
  std::cout<<"Enter the Message :";
  std::getline(std::cin,buff);
  int len=buff.length();
  rc=zmq_msg_init_data (&msg, (void*)buff.c_str(), len, NULL, NULL);
  rc = zmq_sendmsg (sockDealer2, &msg, 0);
  std::cout<<",Size of message sent :"<<rc<<"\n";
  assert(rc>0);
  rc = zmq_msg_close (&msg);
 if(rc !=0)
 {
   std::cout<<"Error in zmq_close()"<<zmq_strerror(errno);
 }
  }

 }
 zmq_close(sockDealer2);
 zmq_ctx_destroy(ctx);_

**server.cpp**
_void *ctx=zmq_ctx_new();
 void *sockDealer1=zmq_socket(ctx,ZMQ_DEALER);
 int rc=zmq_bind(sockDealer1,"tcp://localhost:6611");
 if(rc!=0)
 {
 std::cout<<"Error in zmq_bind() :"<<zmq_strerror (errno);
 }
 else
 {
 std::cout<<"Bind Successfull\n";
 int i;
// for(i=0;i<5;i++){
 while(1){
 zmq_msg_t msg;
 rc = zmq_msg_init (&msg);
 int nbytes=-1;
 char buff[20];
 memset(buff,0,sizeof(buff));
 int rc=-1;
 rc=zmq_recvmsg(sockDealer1,&msg,0);

 memcpy (buff,zmq_msg_data(&msg), rc);
 std::cout<<"Buff Received is :"<<buff<<"\n";
 rc = zmq_msg_close (&msg);
    if (rc != 0) {
        std::cout<<"error in zmq_msg_close: "<< zmq_strerror (errno)<<"\n";
        return -1;
    }
   }
}
 zmq_close(sockDealer1);
 zmq_ctx_destroy(ctx);_

**Comment by Prachi2807** [comment] 2016-09-20 18:06
Are you able to reproduce the problem??

**Comment by Prachi2807** [comment] 2016-09-21 12:23
Hi,
Do you tried the issue??

**Comment by bluca** [comment] 2016-09-21 12:47
Hi, sorry didn't have time yet

**Comment by Prachi2807** [comment] 2016-09-21 13:28
R u able to run it??

**Comment by bluca** [comment] 2016-09-24 12:54
Hi,

The problem is in your client code. Please read the API docs: http://api.zeromq.org/4-1:zmq-msg-init-data
zmq_msg_init_data takes ownership of the pointer you pass, and will free it once done with the callback you pass as third argument.

What's happening in your client is that the string pointer goes out of scope, and that means all bets are off.

If you start the server first it's quick enough that it doesn't matter, but if the client starts first the messages are queued and then read later, when your string has been deallocated already.

To fix it in your example, use zmq_init_size and copy the string in:

```
	  rc = zmq_msg_init_size (&msg, len);
	  memcpy(zmq_msg_data(&msg), (void *) buff.c_str (), len);
```

**Closed by bluca** 2016-09-24 12:54 UTC

**Comment by Prachi2807** [comment] 2016-09-26 09:39
Thanks @bluca  :-)

**Comment by kkbachu** [comment] 2019-05-09 20:56
I was about to open a new issue but bumped into this issue that is closed. Not sure how to reopen it.
In the same problem description above,
server is started first, ensured that it is started.
client connects to it and start sending 10 messages.
Each message does like below -
      zmq_msg_init_size(&msg, len);
      memcpy(zmq_msg_data(&msg), buffer, len);
     zmq_msg_send(&msg, zmq_sock, 0) ;
Each buffer is really a struct like below -
typedef struct message {
      char *buf; // malloced
      int seq;
  } message_t;
Router always receives the last message.
If I put a sleep(1) between each zmq_msg_send(), then it works as expected. But putting a sleep is not a ideal solution.
Appreciate the help.

**Comment by hoditohod** [comment] 2019-05-10 11:49
Do I get it right? You're passing a struct containing a pointer to libzmq by (struct) address and length?

This is bad, zmq will not send the string pointed by buf, only the pointer. You need to properly serialize your data (for example: JSON/BSON/MsgPack/etc...) before passing it to libzmq.

**Comment by kkbachu** [comment] 2019-05-10 17:48
void *buffer = (message_t*)malloc(sizeof(message_t);
But message_t contains char*buf that is malloced as well.
When I do zmq_msg_init_size(&msg, len) --len is the whole size of the struct including the buffer pointer.
This works for REQ/REP but doesn't work with DEALER/ROUTER.

**Comment by hoditohod** [comment] 2019-05-13 07:06
As I said before: you can't pass a pointer inside a message. It memory referenced by the pointer is not sent, only the pointer itself. It will crash if the receiver is a different process, and you'll experience strange behavior/crash if the receiver is in the same process as the sender.

For the sake of test replace `char* buf` with `char buf[1024]` in your struct, and you'll see it works. (This effectively inlines the buffer into the struct.)
