### ISSUE TITLE
Assertion failed: false (src/pipe.cpp:424) on SUB-socket disconnect

### ISSUE THREAD

**Issue by acachy** [zeromq/libzmq#2293] opened 2017-01-06 05:40 UTC
Tested on Debian 8 x64 + PHP7 + mkoppanen php-zmq + libzmq 2.1.5 \ 2.2.0 \ 2.2.1 and other versions. 

Case:
- SUB-socket connect to 1 or 2 PUB-endpoints by tcp
- Process few messages
- Get endpoints list by $socket->getEndpoints()
- Try to disconnect each endpoint by $socket->disconnect($endpoint)

Result:
- If have only 1 endpoint - it dies with "Segmentation fault"
- If have 2 endpoints - it dies on the first disconnect-try with "Assertion failed: false (src/pipe.cpp:424)" (line 418 on some previous versions)

With other socket-types or if disconnect made just after connection - there are no problems.

**Comment by bluca** [comment] 2017-01-06 08:27
Can you reproduce the problem using only libzmq? If so can you share the code?

**Comment by acachy** [comment] 2017-01-09 17:25
Unfortunately, for now I have experience only in usage through php-bindings. And if such case could be caused by bindings - I think it must be them, don't waste your time anymore.

**Comment by bluca** [comment] 2017-01-09 17:29
Have you tried searching on the php issue tracker and opening a ticket there if nothing is already there?

**Comment by acachy** [comment] 2017-01-10 04:13
It's really because of mkoppanen-bindings, which I've successfully used over year with php7.

The problem was solved by changing to the more fresh alternative bindings-library from unstable debian repository 
https://packages.debian.org/sid/php-zmq

**Comment by bluca** [comment] 2017-01-10 08:47
Thanks for confirming the problem is solved with the newer binding, closing the issue then

**Closed by bluca** 2017-01-10 08:47 UTC
