### ISSUE TITLE
zmq doesn't throw on invalid URI in connect()

### ISSUE THREAD

**Issue by Jehannum505** [zeromq/libzmq#2931] opened 2018-02-08 17:27 UTC
# Issue description
In 4.1.5, zmq would throw if a bad URI were passed in.  4.2.3 does not.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: RH7

# Minimal test code / Steps to reproduce the issue

1.  use your java of choice to run:

import org.zeromq.ZMQ;

// connect to an invalid uri:
// tcp://invalid_uri:1234

public class Connector {

    public static void main(String[] args) throws Exception {
        ZMQ.Context context = ZMQ.context(1);
        ZMQ.Socket socket = context.socket(ZMQ.REQ);
        try {
            socket.connect("tcp://invalid_uri:1234");
        }
        catch (Exception ex) {
            System.out.println("Error connecting to uri 'tcp://invalid_uri:1234'");
            return;
        }
        System.out.println("No error caught connecting to invalid URI");
        socket.close();
        context.term();
    }
}

# What's the actual result? (include assertion message & call stack if applicable)
No error caught connecting to invalid URI

# What's the expected result?
Error connecting to uri 'tcp://invalid_uri:1234'

(edits to clarify)

**Comment by sigiesec** [comment] 2018-02-08 17:32
There is no libzmq version 5.1.3. Did you mean 4.1.3?

**Comment by bluca** [comment] 2018-02-08 18:01
Could you please specify which previous versions you are referring to? IIRC we never did DNS resolution synchronously, it was always done by the I/O thread

**Comment by Jehannum505** [comment] 2018-02-08 20:51
I'm sorry, I meant version 4.2.3.

**Comment by Jehannum505** [comment] 2018-02-08 20:53
@bluca: this was an upgrade from 4.1.5.

**Comment by bluca** [comment] 2018-02-08 22:15
I just checked and in 4.1.x doing a connect("tcp://lol.no:1234") does not return an error. Are you sure it's not something coming from the Java layer?

**Comment by Jehannum505** [comment] 2018-02-08 22:17
@bluca, that is possible, the system also has jzmq-3.1.1 installed.

**Comment by bluca** [comment] 2018-02-08 22:30
Then I would recommend to open this on jzmq repository, unless you can provide a C-only example that when compiled with 4.1.x errors out and now doesn't.

**Comment by bluca** [comment] 2018-03-01 11:20
@Jehannum505 closing since this does not appear to have changed in libzmq. Please reopen if you manage to reproduce a regression using only libzmq, without the Java layer.

**Closed by bluca** 2018-03-01 11:20 UTC
Labels: Area (Runtime / Usage), Symptom (Unexpected behavior)
