### ISSUE TITLE
Problem: infinite hwm of version 4.2 lead to catch no msg 

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/libzmq#2228] opened 2016-11-28 02:59 UTC
In release version of 4.2, we got a change in `zmq::pipe_t::set_hwms`, that 0 means infinite hwm.
```C++
 void zmq::pipe_t::set_hwms (int inhwm_, int outhwm_)
 {
     int in = inhwm_ + inhwmboost;
     int out = outhwm_ + outhwmboost;
 
     // if either send or recv side has hwm <= 0 it means infinite so we should set hwms infinite
     if (inhwm_ <= 0 || inhwmboost <= 0)
         in = 0;
 
     if (outhwm_ <= 0 || outhwmboost <= 0)
         out = 0;
 
     lwm = compute_lwm(in);
     hwm = out;
 }
```
but in some case ,I use the dealer mode, and **set sndhwm after connect**, lead to the hwm and lwm eq 0. which is not my origin idea.

Then if one side (dealer mode)(side A) is infinite hwm, and another (router mode)(side B) set hwm to a limit number. Then A side will never send_activate_write  to the peer, accoding to the follow code.
```C++
    if (lwm > 0 && msgs_read % lwm == 0)
        send_activate_write (peer, msgs_read);
```

Finally, we got a full hwm by check_hwm, and reset_pollin. Since then, no message can be caught.

**Comment by bluca** [comment] 2016-11-30 13:26
This was changed to fix a bug, can't remember which, I'll dig it up later today

**Comment by bluca** [comment] 2016-12-01 23:19
So I was thinking of this: https://github.com/zeromq/libzmq/pull/1649 but that's unrelated, I think.

Looking at the documentation, 0 meant infinite already in 2.1, so this hasn't really changed: http://api.zeromq.org/2-1:zmq-setsockopt

What changed is that now it's possible to modify the HWMs even after a bind/connect, since this PR: https://github.com/zeromq/libzmq/pull/1426 Is this what's causing you a problem?

Would you be able to upload to gist/pastebin a minimal test case that reproduces the issue you are facing? Thanks!

**Comment by IA-32** [comment] 2016-12-04 09:04
@bluca I just write a test case follow
[https://gist.github.com/IA-32/40374e2b40a5bfec56c7ce69749418eb](url)

**Comment by IA-32** [comment] 2016-12-04 09:15
@bluca  I just write a test case: 
[https://gist.github.com/IA-32/40374e2b40a5bfec56c7ce69749418eb](https://gist.github.com/IA-32/40374e2b40a5bfec56c7ce69749418eb)

In my test case, I write some code to simulate a normal service, which is that frontend svr send msg to backend svr, and wish to recv response from backend.

and in the code, frontend svr set hwm after connect, and send total 5000 msg (should bigger than default hwm 1000)

and if I build this code with version 4.1.6, I can get what I expected
![image](https://cloud.githubusercontent.com/assets/7036040/20865135/d755aa50-ba44-11e6-8f88-20d603a4dae8.png)

then, I build with 4.2.0, I can only recv 1000 msg from backend.
![image](https://cloud.githubusercontent.com/assets/7036040/20865131/9c518b04-ba44-11e6-90c4-5536612fb1a9.png)

**Comment by bluca** [comment] 2017-01-06 22:00
The gist is not longer visible

**Comment by laplaceyang** [comment] 2017-01-08 13:06
@bluca 
[`https://gist.github.com/laplaceyang/40374e2b40a5bfec56c7ce69749418eb`](https://gist.github.com/laplaceyang/40374e2b40a5bfec56c7ce69749418eb)

here is the gist

**Comment by laplaceyang** [comment] 2017-01-10 13:23
@bluca I just wrote a thread-safe solution by using command ,and include your pr. 

https://github.com/laplaceyang/libzmq/commit/3062a976e8edadcc192d3e8a20ba4ee6da20f2e2

By simply test, it works. But afraid of include some mistake.

**Comment by bluca** [comment] 2017-01-10 13:31
Thank you for taking care of it! I can have a look in detail later tonight

**Comment by bluca** [comment] 2017-01-11 00:15
@laplaceyang that looks fine to me. Would you please rebase it and send a PR?

**Comment by laplaceyang** [comment] 2017-01-11 02:54
@bluca pr has send, also with rebase my commit. [https://github.com/zeromq/libzmq/pull/2302](https://github.com/zeromq/libzmq/pull/2302)

**Comment by bluca** [comment] 2017-01-11 08:41
Thank you for fixing this! Closing as it's solved by PR https://github.com/zeromq/libzmq/pull/2302

**Closed by bluca** 2017-01-11 08:41 UTC
