### ISSUE TITLE
segfault when called from pyzmq

### ISSUE THREAD

**Issue by dionyziz** [zeromq/libzmq#1175] opened 2014-09-05 16:04 UTC
More details can be found here:

https://github.com/zeromq/pyzmq/issues/583

This causes the whole python instance to crash completely.

**Comment by sublee** [comment] 2017-04-06 07:11
I have a similar issue.  `Bad file descriptor (src/signaler.cpp:301)`

**Comment by bluca** [comment] 2017-04-06 08:57
Can you give us more details please?
Platform, versions? What is your code doing? Can you share a minimal example to reproduce the issue?

**Comment by sublee** [comment] 2017-04-06 09:11
It was libzmq-4.1.6 on Ubuntu 16.04.

I guess this is a thread-safe issue.  There was my mistake.  So one zmq socket is touched in 2 threads each for `recv`/`send` and `bind`.

**Comment by bluca** [comment] 2017-04-06 09:32
Yes, that is not allowed.
Is it working fine now? Can we close the issue then?

**Comment by sublee** [comment] 2017-04-06 10:37
In my case, yes.  But I'm not sure @dionyziz also has same cause.

**Comment by sigiesec** [comment] 2017-08-23 18:55
I'm closing the issue then.
@dionyziz if the issue is still unresolved for you, please reopen

**Closed by sigiesec** 2017-08-23 18:55 UTC
