### ISSUE TITLE
Problem: build scripts not compatible with Android NDK r17

### ISSUE THREAD

**Issue by cpicanco** [zeromq/libzmq#3165] opened 2018-06-14 00:05 UTC
# Issue description
I am trying to cross-compile for android and I am getting a `configure: error: C compiler cannot create executables` error. I am missing something in the enviroment configuration, of course. What should I do to make the build script happy?

# Environment

* libzmq version (0867c380326829dc7e48e12d46b977bffad207c4): 
* OS: Ubuntu 16.04 LTS

# Minimal test code / Steps to reproduce the issue

1. Install android studio.
2. Download sdk through the built in manager (23, 24, 28).
3. Download ndk through the built in manager (r17).
5. Configure your environment:

```bash
export ANDROID_NDK_ROOT=${HOME}/Android/Sdk/ndk-bundle
export TOOLCHAIN_NAME=arm-linux-androideabi-4.9
export TOOLCHAIN_HOST=arm-linux-androideabi
export TOOLCHAIN_PATH=${ANDROID_NDK_ROOT}/toolchains/${TOOLCHAIN_NAME}/prebuilt/linux-x86_64/bin
export TOOLCHAIN_ARCH=arm
```
6. Run build.sh

# What's the actual result? (include assertion message & call stack if applicable)

```text
$ export ANDROID_NDK_ROOT=${HOME}/Android/Sdk/ndk-bundle
$ export TOOLCHAIN_NAME=arm-linux-androideabi-4.9
$ export TOOLCHAIN_HOST=arm-linux-androideabi
$ export TOOLCHAIN_PATH=${ANDROID_NDK_ROOT}/toolchains/${TOOLCHAIN_NAME}/prebuilt/linux-x86_64/bin
$ export TOOLCHAIN_ARCH=arm
$ ~/libzmq/builds/android$ ./build.sh 
make: *** No rule to make target 'clean'.  Stop.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
libtoolize: copying file 'config/libtool.m4'
libtoolize: copying file 'config/ltoptions.m4'
libtoolize: copying file 'config/ltsugar.m4'
libtoolize: copying file 'config/ltversion.m4'
libtoolize: copying file 'config/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --include=config --force
autoreconf: running: /usr/bin/autoheader --include=config --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:58: installing 'config/compile'
configure.ac:74: installing 'config/config.guess'
configure.ac:74: installing 'config/config.sub'
configure.ac:14: installing 'config/install-sh'
configure.ac:14: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
parallel-tests: installing 'config/test-driver'
autoreconf: Leaving directory `.'
configure: error: in `/home/rafael/android_build/arm-linux-androideabi-4.9/libzmq':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
> config.log
```text
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by zeromq configure 4.3.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --quiet CC=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc CXX=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ LD=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld AS=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-as AR=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar RANLIB=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib CFLAGS=--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include  CPPFLAGS=--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include  CXXFLAGS=--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include  LDFLAGS=-L/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib -L/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi  LIBS=-lc -lgcc -ldl  -lrt -lpthread -lgcc -lsupc++ -lstdc++ -lgnustl_shared  PKG_CONFIG_PATH=/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib/pkgconfig --host=arm-linux-androideabi --prefix=/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9 --disable-curve --without-docs

## --------- ##
## Platform. ##
## --------- ##

hostname = ft-lab
uname -m = x86_64
uname -r = 4.4.0-127-generic
uname -s = Linux
uname -v = #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/rafael/.rubies/ruby-2.5.0/bin
PATH: /home/rafael/bin
PATH: /home/rafael/.local/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games
PATH: /snap/bin
PATH: /home/rafael/Android/Sdk/tools
PATH: /home/rafael/Android/Sdk/platform-tools
PATH: /home/rafael/Android/Sdk/ndk-bundle
PATH: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin
PATH: /home/rafael/git/castle-engine/tools/build-tool


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2961: checking for a BSD-compatible install
configure:3029: result: /usr/bin/install -c
configure:3040: checking whether build environment is sane
configure:3095: result: yes
configure:3154: checking for arm-linux-androideabi-strip
configure:3170: found /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
configure:3181: result: arm-linux-androideabi-strip
configure:3246: checking for a thread-safe mkdir -p
configure:3285: result: /bin/mkdir -p
configure:3292: checking for gawk
configure:3308: found /usr/bin/gawk
configure:3319: result: gawk
configure:3330: checking whether make sets $(MAKE)
configure:3352: result: yes
configure:3381: checking whether make supports nested variables
configure:3398: result: yes
configure:3487: checking whether UID '1000' is supported by ustar format
configure:3490: result: yes
configure:3497: checking whether GID '1000' is supported by ustar format
configure:3500: result: yes
configure:3508: checking how to create a ustar tar archive
configure:3519: tar --version
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
configure:3522: $? = 0
configure:3562: tardir=conftest.dir && eval tar --format=ustar -chf - "$tardir" >conftest.tar
configure:3565: $? = 0
configure:3569: tar -xf - <conftest.tar
configure:3572: $? = 0
configure:3574: cat conftest.dir/file
GrepMe
configure:3577: $? = 0
configure:3590: result: gnutar
configure:3961: checking whether make supports nested variables
configure:3978: result: yes
configure:4033: checking for arm-linux-androideabi-gcc
configure:4060: result: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
configure:4329: checking for C compiler version
configure:4338: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --version >&5
arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4349: $? = 0
configure:4338: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -v >&5
Using built-in specs.
COLLECT_GCC=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
COLLECT_LTO_WRAPPER=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../libexec/gcc/arm-linux-androideabi/4.9.x/lto-wrapper
Target: arm-linux-androideabi
Configured with: /usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/configure --prefix=/tmp/1f702185e9cc53b747a5c4e1441c9254 --target=arm-linux-androideabi --host=x86_64-linux-gnu --build=x86_64-linux-gnu --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --with-gmp=/buildbot/tmp/build/toolchain/temp-install --with-mpfr=/buildbot/tmp/build/toolchain/temp-install --with-mpc=/buildbot/tmp/build/toolchain/temp-install --with-cloog=/buildbot/tmp/build/toolchain/temp-install --with-isl=/buildbot/tmp/build/toolchain/temp-install --with-ppl=/buildbot/tmp/build/toolchain/temp-install --disable-ppl-version-check --disable-cloog-version-check --disable-isl-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-float=soft --with-fpu=vfp --with-arch=armv5te --enable-target-optspace --enable-bionic-libs --enable-libatomic-ifuncs=no --enable-initfini-array --disable-nls --prefix=/tmp/1f702185e9cc53b747a5c4e1441c9254 --with-sysroot=/tmp/1f702185e9cc53b747a5c4e1441c9254/sysroot --with-binutils-version=2.27 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gmp-version=5.0.5 --with-gcc-version=4.9 --with-gdb-version=none --with-gxx-include-dir=/tmp/1f702185e9cc53b747a5c4e1441c9254/include/c++/4.9.x --with-bugurl=http://source.android.com/source/report-bugs.html --enable-languages=c,c++ --disable-bootstrap --enable-plugins --enable-libgomp --enable-gnu-indirect-function --disable-libsanitizer --enable-gold --enable-threads --enable-eh-frame-hdr-for-static --enable-graphite=yes --with-isl-version=0.11.1 --with-cloog-version=0.18.0 --with-arch=armv5te --program-transform-name='s&^&arm-linux-androideabi-&' --enable-gold=default
Thread model: posix
gcc version 4.9.x 20150123 (prerelease) (GCC) 
configure:4349: $? = 0
configure:4338: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -V >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-V'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:4349: $? = 1
configure:4338: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -qversion >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-qversion'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:4349: $? = 1
configure:4369: checking whether the C compiler works
configure:4391: /home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include  --sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include  -L/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib -L/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi  conftest.c -lc -lgcc -ldl  -lrt -lpthread -lgcc -lsupc++ -lstdc++ -lgnustl_shared  >&5
/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lsupc++
/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgnustl_shared
collect2: error: ld returned 1 exit status
configure:4395: $? = 1
configure:4433: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "zeromq"
| #define PACKAGE_TARNAME "zeromq"
| #define PACKAGE_VERSION "4.3.1"
| #define PACKAGE_STRING "zeromq 4.3.1"
| #define PACKAGE_BUGREPORT "zeromq-dev@lists.zeromq.org"
| #define PACKAGE_URL ""
| #define PACKAGE "zeromq"
| #define VERSION "4.3.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4438: error: in `/home/rafael/android_build/arm-linux-androideabi-4.9/libzmq':
configure:4440: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_ASCIIDOC_set=
ac_cv_env_ASCIIDOC_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include '
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include '
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib -L/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi '
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value='-lc -lgcc -ldl  -lrt -lpthread -lgcc -lsupc++ -lstdc++ -lgnustl_shared '
ac_cv_env_LIBUNWIND_CFLAGS_set=
ac_cv_env_LIBUNWIND_CFLAGS_value=
ac_cv_env_LIBUNWIND_LIBS_set=
ac_cv_env_LIBUNWIND_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=set
ac_cv_env_PKG_CONFIG_PATH_value=/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib/pkgconfig
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_XMLTO_set=
ac_cv_env_XMLTO_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_gssapi_krb5_CFLAGS_set=
ac_cv_env_gssapi_krb5_CFLAGS_value=
ac_cv_env_gssapi_krb5_LIBS_set=
ac_cv_env_gssapi_krb5_LIBS_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=arm-linux-androideabi
ac_cv_env_norm_CFLAGS_set=
ac_cv_env_norm_CFLAGS_value=
ac_cv_env_norm_LIBS_set=
ac_cv_env_norm_LIBS_value=
ac_cv_env_pgm_CFLAGS_set=
ac_cv_env_pgm_CFLAGS_value=
ac_cv_env_pgm_LIBS_set=
ac_cv_env_pgm_LIBS_value=
ac_cv_env_sodium_CFLAGS_set=
ac_cv_env_sodium_CFLAGS_value=
ac_cv_env_sodium_LIBS_set=
ac_cv_env_sodium_LIBS_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_CC=/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
ac_cv_prog_STRIP=arm-linux-androideabi-strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes
am_cv_prog_tar_ustar=gnutar

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/missing aclocal-1.15'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar'
AS='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-as'
ASCIIDOC=''
AUTOCONF='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/missing autoconf'
AUTOHEADER='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/missing autoheader'
AUTOMAKE='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/missing automake-1.15'
AWK='gawk'
BUILD_DOC_FALSE=''
BUILD_DOC_TRUE=''
BUILD_GSSAPI_FALSE=''
BUILD_GSSAPI_TRUE=''
BUILD_TIPC_FALSE=''
BUILD_TIPC_TRUE=''
CC='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'
CCDEPMODE=''
CFLAGS='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include '
CLANG_FORMAT=''
CODE_COVERAGE_CFLAGS=''
CODE_COVERAGE_CPPFLAGS=''
CODE_COVERAGE_CXXFLAGS=''
CODE_COVERAGE_ENABLED=''
CODE_COVERAGE_ENABLED_FALSE=''
CODE_COVERAGE_ENABLED_TRUE=''
CODE_COVERAGE_LDFLAGS=''
CODE_COVERAGE_LIBS=''
CODE_COVERAGE_RULES=''
CPP=''
CPPFLAGS='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include '
CXX='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='--sysroot=/home/rafael/Android/Sdk/ndk-bundle/platforms/android-14/arch-arm -I/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/include '
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_ASAN_FALSE=''
ENABLE_ASAN_TRUE=''
ENABLE_CURVE_KEYGEN_FALSE=''
ENABLE_CURVE_KEYGEN_TRUE=''
ENABLE_DRAFTS_FALSE=''
ENABLE_DRAFTS_TRUE=''
ENABLE_PERF_FALSE=''
ENABLE_PERF_TRUE=''
ENABLE_STATIC_FALSE=''
ENABLE_STATIC_TRUE=''
EXEEXT=''
FGREP=''
GCOV=''
GENHTML=''
GREP=''
HAVE_CURVE_FALSE=''
HAVE_CURVE_TRUE=''
HAVE_CXX11=''
HAVE_FORK_FALSE=''
HAVE_FORK_TRUE=''
HAVE_IPC_PEERCRED_FALSE=''
HAVE_IPC_PEERCRED_TRUE=''
HAVE_NORM_FALSE=''
HAVE_NORM_TRUE=''
HAVE_PGM_FALSE=''
HAVE_PGM_TRUE=''
HAVE_VMCI_FALSE=''
HAVE_VMCI_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_MAN_FALSE=''
INSTALL_MAN_TRUE=''
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LCOV=''
LD='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld'
LDFLAGS='-L/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib -L/home/rafael/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi '
LIBOBJS=''
LIBS='-lc -lgcc -ldl  -lrt -lpthread -lgcc -lsupc++ -lstdc++ -lgnustl_shared '
LIBTOOL=''
LIBUNWIND_CFLAGS=''
LIBUNWIND_LIBS=''
LIBZMQ_EXTRA_CFLAGS=''
LIBZMQ_EXTRA_CXXFLAGS=''
LIBZMQ_EXTRA_LDFLAGS=''
LIBZMQ_VMCI_CXXFLAGS=''
LIBZMQ_VMCI_LDFLAGS=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LTVER='6:6:1'
LT_SYS_LIBRARY_PATH=''
MAKEINFO='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
ON_ANDROID_FALSE=''
ON_ANDROID_TRUE=''
ON_CYGWIN_FALSE=''
ON_CYGWIN_TRUE=''
ON_GNU_FALSE=''
ON_GNU_TRUE=''
ON_LINUX_FALSE=''
ON_LINUX_TRUE=''
ON_MINGW_FALSE=''
ON_MINGW_TRUE=''
OTOOL64=''
OTOOL=''
PACKAGE='zeromq'
PACKAGE_BUGREPORT='zeromq-dev@lists.zeromq.org'
PACKAGE_NAME='zeromq'
PACKAGE_STRING='zeromq 4.3.1'
PACKAGE_TARNAME='zeromq'
PACKAGE_URL=''
PACKAGE_VERSION='4.3.1'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH='/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9/lib/pkgconfig'
RANLIB='/home/rafael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP='arm-linux-androideabi-strip'
USE_LIBSODIUM_FALSE=''
USE_LIBSODIUM_TRUE=''
USE_TWEETNACL_FALSE=''
USE_TWEETNACL_TRUE=''
USE_WEPOLL_FALSE=''
USE_WEPOLL_TRUE=''
VALGRIND=''
VALGRIND_CHECK_RULES=''
VALGRIND_ENABLED=''
VALGRIND_ENABLED_FALSE=''
VALGRIND_ENABLED_TRUE=''
VALGRIND_HAVE_TOOL_drd=''
VALGRIND_HAVE_TOOL_exp_sgcheck=''
VALGRIND_HAVE_TOOL_helgrind=''
VALGRIND_HAVE_TOOL_memcheck=''
VERSION='4.3.1'
WITH_CLANG_FORMAT=''
WITH_CLANG_FORMAT_FALSE=''
WITH_CLANG_FORMAT_TRUE=''
XMLTO=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='tar --format=ustar -chf - "$$tardir"'
am__untar='tar -xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
gssapi_krb5_CFLAGS=''
gssapi_krb5_LIBS=''
host='arm-linux-androideabi'
host_alias='arm-linux-androideabi'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/rafael/android_build/arm-linux-androideabi-4.9/libzmq/config/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libzmq_have_asciidoc=''
libzmq_have_xmlto=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
norm_CFLAGS=''
norm_LIBS=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
pgm_CFLAGS=''
pgm_LIBS=''
pkg_config_defines=''
pkg_config_libs_private=''
pkgconfigdir=''
prefix='/home/rafael/git/castle-engine/examples/libzmq/builds/android/prefix/arm-linux-androideabi-4.9'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sodium_CFLAGS=''
sodium_LIBS=''
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "zeromq"
#define PACKAGE_TARNAME "zeromq"
#define PACKAGE_VERSION "4.3.1"
#define PACKAGE_STRING "zeromq 4.3.1"
#define PACKAGE_BUGREPORT "zeromq-dev@lists.zeromq.org"
#define PACKAGE_URL ""
#define PACKAGE "zeromq"
#define VERSION "4.3.1"

configure: exit 77
```

# What's the expected result?

Cross compiled libzmq.so.

**Comment by bluca** [comment] 2018-06-17 14:42
The current scripts are not compatible with the latest version of the NDK. Someone needs to fix them. Feel free to send a PR.

**Comment by bluca** [comment] 2018-06-17 14:43
Closing as duplicate of https://github.com/zeromq/libzmq/issues/2894

**Closed by bluca** 2018-06-17 14:43 UTC
Labels: Area (Build/Compilation), Help Request, Platform (linux/android)
