### ISSUE TITLE
Open file leak during DNS resolution while network is down (regression in libzmq-4.1.0 and libzmq-master)

### ISSUE THREAD

**Issue by tkrajca** [zeromq/libzmq#1302] opened 2015-01-14 01:35 UTC
Hi,

I am pretty confident I found a file leak in the way libzmq does DNS resolution while network is down. I successfully verified this bug against libzmq-4.1.0 and libzmq master on github. This bug is not in libzmq-4.0.5 so it must have been introduced somewhere in between 4.0.5 and 4.1.0.

Sorry, I am not a C programmer so this is how to reproduce it in python but it should be pretty obvious anyway.

I've got a SUB client that periodically polls for messages, if it does not see any messages, it reconnects (shuts itself down, unregisters from the poller, creates itself again and reregisters with the poller). Simple, standard. Let's assume it never sees any messages, for example because the PUB server is down.

1) Everything works fine when I hard code the IP address of the server to 192.168.13.1 so that there is no DNS resolution.

I run a SUB client that connects to tcp://192.168.13.1:4141. There is nothing listening on tcp://192.168.13.1:4141 - it does not matter whether there is a server or not, the issue is still there. I continually check number of open files on this python process in bash with:

```
while true; do lsof -n -p <pid>; sleep 1s; done
```

The number of open files sits around 42. Then I unplug the network cable - 192.168.13.1 is not reachable any more - and keep watching the number of open files. It still sits around 42. I plug the cable back in to make 192.168.13.1 available again. The number of open files still sits around 42. Everything is happy, the way it should be.

2) If I replace the 192.168.13.1 with its DNS name, e.g. test.example.com so that there is a DNS resolution happening, I see number of open files growing arbitrarily. The number of open files starts around 42 again, as expected. As soon as I unplug the network cable, the number of open files starts growing. It seems to grow with every SUB reconnect. This is not a temporary issue, we saw it grow for about an hour until it exhausted all available file handles. When I plug the network cable back in, the number of open files drops back to 42.

I think this pretty clearly looks like a file leak during DNS resolution while network is down.

```
import zmq
import os


def reconnect(context, poller):
    socket = context.socket(zmq.SUB)
    socket.connect("tcp://192.168.13.1:4141")
    socket.setsockopt(zmq.SUBSCRIBE, "")
    poller.register(socket, zmq.POLLIN)
    return socket


if __name__ == "__main__":
    print os.getpid()

    context = zmq.Context()
    poller = zmq.Poller()
    socket = reconnect(context, poller)

    while True:
        print "poller"
        socks = dict(poller.poll(timeout=1000))

        if socket in socks:
            print socket.recv_multipart()
        else:
            poller.unregister(socket)
            socket.close()
            socket = reconnect(context, poller)
```

**Comment by tkrajca** [comment] 2015-01-20 04:00
Here is a simple C code to reproduce the error:

```
#include "zmq.h"
#include "stdio.h"
#include "unistd.h"
#include "string.h"


void * reconnect(void *context)
{
    void *subscriber = zmq_socket (context, ZMQ_SUB);
    zmq_connect(subscriber, "tcp://test.example.com:1234");
    zmq_setsockopt (subscriber, ZMQ_SUBSCRIBE, "", 0);

    return subscriber;
}


int main (void)
{
    //  Start child threads
    void *context = zmq_ctx_new ();
    void *subscriber = reconnect(context);

    while (1) {
        printf("Loop :)\n");
        sleep(1);

        zmq_close(subscriber);
        subscriber = reconnect(context);
    }

    return 0;
}
```
The number of open files sits around 37-38 but as soon as I unplug my network cable this number starts to grow arbitrarily.

**Comment by tkrajca** [comment] 2015-01-20 05:46
Even more simple:

```
#include "zmq.h"
#include "stdio.h"
#include "unistd.h"


int main ()
{
    void *context = zmq_ctx_new();
    void *subscriber;
    while (1) {
        printf("Loop :)\n");
        sleep(1);
        subscriber = zmq_socket (context, ZMQ_SUB);
        zmq_connect(subscriber, "tcp://test.example.com:1234");
        zmq_close(subscriber);
    }
    return 0;
}
```

**Comment by tkrajca** [comment] 2015-04-09 06:11
I think I have hit this issue again :(

http://lists.zeromq.org/pipermail/zeromq-dev/2015-April/028730.html

**Comment by bluca** [comment] 2017-01-03 20:19
Can't reproduce anymore neither with libzmq master nor with 4.0.8, so closing. Please reopen if you still see this.

**Closed by bluca** 2017-01-03 20:19 UTC
