### ISSUE TITLE
Assertion failure in lb.cpp:110

### ISSUE THREAD

**Issue by hashstat** [zeromq/libzmq#1452] opened 2015-06-26 21:13 UTC
I have a [project](/VOLTTRON/volttron) that was working great until I set ZMQ_IMMEDIATE on the client socket. Now I occasionally see the following assertion failure when connecting clients:

```
Assertion failed: !more (src/lb.cpp:110)
Aborted (core dumped)
```

I put together a minimal program to expose the issue. It seems to appear when I attempt to connect to a CURVE server without setting any keys on the client socket, set the ZMQ_IMMEDIATE option on the client, and send multi-part data. It also seems that a slight delay between sends exacerbates the issue.

``` c
#include <assert.h>
#include <unistd.h>

#include <zmq.h>

#define ADDRESS "tcp://127.0.0.1:14321"

static const char *SERVER_SECRETKEY = "JTKVSB%%)wK0E.X)V>+}o?pNmC{O&4W4b!Ni{Lh6";

static void server(void)
{
    void *context, *sock;
    int rc;
    zmq_pollitem_t event = {.socket = NULL, .fd = -1,
                             .events = ZMQ_POLLIN | ZMQ_POLLERR};

    assert ((context = zmq_ctx_new()));
    assert ((sock = zmq_socket(context, ZMQ_DEALER)));
    rc = 1;
    assert (!zmq_setsockopt(sock, ZMQ_CURVE_SERVER, &rc, sizeof(rc)));
    assert (!zmq_setsockopt(sock, ZMQ_CURVE_SECRETKEY, SERVER_SECRETKEY, 40));
    assert (!zmq_bind(sock, ADDRESS));

    event.socket = sock;

    while ((rc = zmq_poll(&event, 1, 1000))) {
        char buf[100];
        assert (rc != -1 && !(event.revents & ZMQ_POLLERR));
        assert (zmq_recv(sock, buf, sizeof(buf), 0) != -1);
    }
}

static void client(void)
{
    void *context, *sock;
    int i;
    zmq_pollitem_t event = {.socket = NULL, .fd = -1,
                             .events = ZMQ_POLLOUT | ZMQ_POLLERR};

    assert ((context = zmq_ctx_new()));
    assert ((sock = zmq_socket(context, ZMQ_DEALER)));
    i = 1;
    assert (!zmq_setsockopt(sock, ZMQ_IMMEDIATE, &i, sizeof(i)));
    assert (!zmq_connect(sock, ADDRESS));

    event.socket = sock;

    for (i = 0; i < 100000; i++) {
        int flags = i % 3 ? ZMQ_SNDMORE : 0;
        zmq_poll(&event, 1, 10);
        assert (zmq_send(sock, "hello", 5, flags) == 5);
    }
    zmq_close(sock);
    zmq_ctx_destroy(context);
}

int main(void)
{
    if (fork())
        client();
    else
        server();
    return 0;
}
```

And here is the backtrace from gdb:

```
Program received signal SIGABRT, Aborted.
0x00007ffff77fd528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff77fd528 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff77fe93a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7b8c359 in zmq::zmq_abort (
    errmsg_=errmsg_@entry=0x7ffff7bc2c8a "!more") at src/err.cpp:84
#3  0x00007ffff7b8f8e8 in zmq::lb_t::sendpipe (this=0x617620, 
    msg_=0x7fffffffe520, pipe_=0x0) at src/lb.cpp:110
#4  0x00007ffff7ba8ec8 in zmq::socket_base_t::send (this=this@entry=0x617160, 
    msg_=msg_@entry=0x7fffffffe520, flags_=flags_@entry=2)
    at src/socket_base.cpp:951
#5  0x00007ffff7bc11fc in s_sendmsg (s_=s_@entry=0x617160, 
    msg_=msg_@entry=0x7fffffffe520, flags_=flags_@entry=2) at src/zmq.cpp:346
#6  0x00007ffff7bc1281 in zmq_send (s_=0x617160, buf_=0x400fb4, len_=5, 
    flags_=2) at src/zmq.cpp:371
#7  0x0000000000400ce1 in client ()
#8  0x0000000000400d43 in main ()
```

I have a feeling that some sort of state is getting out of sync after the failed authentication attempts.

**Comment by hashstat** [comment] 2015-06-26 21:33
By the way, I attempted both with the master branch and v4.1.2 with the same result. I am using Arch Linux with kernel 4.0.5-1.

You may need to fiddle with the poll timeout and the number of iterations in the client if the bug isn't appearing.

Also, this issue is probably minor as clients and servers should match their encryption state, but it is kind of a bummer to see a segfault instead of a timeout or error message. Thanks.

**Comment by wcs1only** [comment] 2015-10-26 15:04
I think #1588 is a duplicate of this issue. Does the #1588 fix work for you?

**Comment by bluca** [comment] 2017-01-03 14:57
Closing since this is a duplicate of a problem fixed by https://github.com/zeromq/libzmq/pull/1600#event-427147892

**Closed by bluca** 2017-01-03 14:57 UTC
