### ISSUE TITLE
Unable to build "master" branch (GCC 5.3.0)

### ISSUE THREAD

**Issue by SchweinDeBurg** [zeromq/libzmq#2666] opened 2017-08-08 14:13 UTC
```
src/session_base.cpp: In member function 'void zmq::session_base_t::start_connecting(bool)':
src/session_base.cpp:634:35: error: invalid new-expression of abstract class type 'zmq::pgm_sender_t'
                 io_thread, options);
                                   ^
In file included from src/session_base.cpp:42:0:
src/pgm_sender.hpp:49:11: note:   because the following virtual functions are pure within 'zmq::pgm_sender_t':
     class pgm_sender_t : public io_object_t, public i_engine
           ^
In file included from src/stream_engine.hpp:36:0,
                 from src/session_base.hpp:40,
                 from src/session_base.cpp:32:
src/i_engine.hpp:62:30: note: 	virtual const char* zmq::i_engine::get_endpoint() const
         virtual const char * get_endpoint() const = 0;
                              ^
src/session_base.cpp:646:35: error: invalid new-expression of abstract class type 'zmq::pgm_receiver_t'
                 io_thread, options);
                                   ^
In file included from src/session_base.cpp:43:0:
src/pgm_receiver.hpp:50:11: note:   because the following virtual functions are pure within 'zmq::pgm_receiver_t':
     class pgm_receiver_t : public io_object_t, public i_engine
           ^
In file included from src/stream_engine.hpp:36:0,
                 from src/session_base.hpp:40,
                 from src/session_base.cpp:32:
src/i_engine.hpp:62:30: note: 	virtual const char* zmq::i_engine::get_endpoint() const
         virtual const char * get_endpoint() const = 0;
                              ^
make[1]: *** [src/src_libzmq_la-session_base.lo] Error 1
make[1]: Leaving directory `/home/elijah/rpmbuild/BUILD/zeromq-4.2.2-git'
make: *** [all-recursive] Error 1
```

**Comment by sigiesec** [comment] 2017-08-08 14:20
@bluca Apparently, pgm is not enabled in any of the CI builds. Can we change that?

**Comment by bluca** [comment] 2017-08-08 14:21
I'm about to send a PR to fix this, just testing it

**Comment by bluca** [comment] 2017-08-08 14:30
We could, but it would make the CI twice as slow, so I would rather not.
It's enable on OBS so in case of failure after a merge, I'll get a notification.

**Comment by sigiesec** [comment] 2017-08-08 14:36
Twice as slow, why? 
What is OBS?
The problem is that for me or anyone else, everything I do not have locally and is also not on CI, is pretty much nonexistent. We do not know if it builds, we do know nothing about the tests. The coverage measurement also does not include it.

**Comment by bluca** [comment] 2017-08-08 14:43
We do know if it builds:

http://zeromq.org/intro:get-the-software (first paragraph)
https://build.opensuse.org/project/show/network:messaging:zeromq:git-stable

I got a notification just after I merged your PR, that's why I already had a change ready.

It would be much slower because it either needs to be either built from scratch or added as a package, and given it would be the first one it apt update would need to be added which takes a couple of minutes

**Comment by sigiesec** [comment] 2017-08-08 14:50
Hm ok. Not optimal. Not really early feedback. And is OBS running any tests, or just the build?

Anyway, thanks for fixing this.

**Comment by bluca** [comment] 2017-08-08 16:17
It's running the tests too, and on way more combinations of distro + stdlib + architecture that could ever be done on travis as you can see in the link. Changes to the base classes internal APIs are so rare that having a post-merge automated check is good enough, without slowing down the pre-merge CI jobs.

**Comment by sigiesec** [comment] 2017-08-08 17:15
Ok, good that the tests are executed!

I think it is okay not to test all platforms pre-merge, but there are significant parts of the code are never executed pre-merge. Internal API changes may be rare, but behavioural changes that might affect these code parts will be more common.

**Closed** 2017-08-08 17:53 UTC
