### ISSUE TITLE
Problem: zmq_msg_send on ZMQ_PUB socket always returns EAGAIN 

### ISSUE THREAD

**Issue by mcorino** [zeromq/libzmq#2230] opened 2016-11-30 11:18 UTC
While trying out a simple pub/sub protocol implementation with 0MQ I ran into a brick wall. I cannot for the life of me get multipart messaging to work using zmq_msg_t frames as I thought it should work based on the 0MQ guide (yes, I read that). In my tests zmq_msg_send() will *ALWAYS* return EAGAIN when attempting to send the key (topic) frame independent of the fact that a subscriber is connected or not.
I am using zmq_msg_t frames since I want to implement a zero-copy protocol (or at least as much as possible).

I checked the guides examples to see if I could find something there that I missed and found there are actually no functioning (C) examples showing this setup anymore (using zmq_msg_t frames) as I am using libzmq v. 4.2.0 and the kvsimple.c based examples are useless with that version.

The closest example I found was pvenvsub.c/pvenvpub.c so I checked these and found it to work properly. This example however did not use zmq_msg_t so I adapted the code to use zmq_msg_t (attached here).
The adapted code again shows my problem by *always* returning EAGAIN in the publisher whether I start the subscriber before running the publisher or not.
Running my adapted publisher shows:

>  ZMQ version 4.2.0
>  zmq_msg_send(env) -> [11]:Resource temporarily unavailable
>  zmq_msg_send(env) -> [11]:Resource temporarily unavailable
>  ...

Is there some change in using this API in the latest versions of 0MQ that I have missed?

[psenvpub_sub_msg.zip](https://github.com/zeromq/libzmq/files/621623/psenvpub_sub_msg.zip)

**Comment by mcorino** [comment] 2016-11-30 11:54
Looking at the libzmq source code in zmq.cpp I cannot understand why I would have these results but I *do*.
When building and running the regular pvenvpub.c from the examples the publisher does as expected: block until the first subscriber connects and then start sending.
When building and running my adapted pvenvpub_msg.c the publisher returns EAGAIN.

Is there a possibility of OS/compiler dependencies? I am on the latest OpenSuSE Tumbleweed using GCC 6.2.1.

**Comment by bluca** [comment] 2016-11-30 12:03
Uh, this looks weird. I use pub-sub all the time, I'll have a look later today

**Comment by bluca** [comment] 2016-11-30 13:04
Right, the problem is in your example, you expect zmq_msg_send to return 0, but as the doc says:

```
The zmq_msg_send() function shall return number of bytes in the message if successful. Otherwise it shall return -1 and set errno to one of the values defined below.
```

And same for the recv.

http://api.zeromq.org/4-2:zmq-msg-send
http://api.zeromq.org/4-2:zmq-msg-recv

**Comment by mcorino** [comment] 2016-11-30 13:20
Oh my ...! You would think I would have learned how to read documentation after all these years but I manage to surprise myself again and again. :-(
Thank you very much for setting me straight again.

**Comment by bluca** [comment] 2016-11-30 13:25
No worries, it's easy to miss these details. I'll close this now since it's solved, please do reopen if you find more issues.

**Closed by bluca** 2016-11-30 13:25 UTC
