### ISSUE TITLE
How does NDK STL changes will affect libzmq cross-compile for android?

### ISSUE THREAD

**Issue by cpicanco** [zeromq/libzmq#3164] opened 2018-06-13 20:26 UTC
According to the ndk roadmap, libstdc++ support will end:

> LLVM's libc++ is the C++ standard library that has been used by the Android OS since Lollipop, and in the future will be the only STL available in the NDK (https://developer.android.com/ndk/guides/cpp-support?hl=en)

Is it of great concern? I am just trying to find out if I will be able to cross-compile libzmq for android in the near future.

Best,
Rafael

**Comment by bluca** [comment] 2018-06-13 22:09
Just try it. You can use llvm's library on any Linux system.

**Comment by bluca** [comment] 2018-06-17 14:43
Duplicate of https://github.com/zeromq/libzmq/issues/2894

**Closed by bluca** 2018-06-17 14:43 UTC
