### ISSUE TITLE
stuck of the whole IO processing because of the sync nature of getaddrinfo() (name resolving)

### ISSUE THREAD

**Issue by rouming** [zeromq/libzmq#3243] opened 2018-09-04 11:55 UTC
Hi all,

Recently I observed that the whole IO processing for particular zmq context can be stuck because of not reliable DNS server. Indeed, getaddrinfo() is a synchronous call and if there are some problems with DNS server all sockets bound to the context where name resolving was taken place will experience huge delay in IO processing.  That means, that if there are already N sockets bound to one zmq context and IO is being successfully processed, any new zmq_connect() call (which requires name resolving) can block whole IO processing for indefinite time.

Again, not zmq_connect() is blocking (which can be a perfect solution, like zmq_bind() does, tries to resolve a hostname blocking the caller), but internally the whole IO thread is blocked, i.e. user of zmq will be blocked in zmq_recv() or zmq_poll() waiting for any event, which can't be processed.

How to reproduce:

1. Modify  /etc/resolv.conf and leave there only 72.66.115.13 (blackhole.webpagetest.org) nameserver, which silently drops all requests, i.e.

nameserver  72.66.115.13

2. Do not forget to disable systemd resolving in /etc/nsswitch.conf, i.e. the following hosts config line should be just:

hosts: files dns

i.e. without "resolve" option, details see here  https://www.freedesktop.org/software/systemd/man/nss-resolve.html)

3. Then just compile and run attached source [stuck-io.c.txt](https://github.com/zeromq/libzmq/files/2348938/stuck-io.c.txt), where one router receives a package each second from a locally connected dealer. On any new package router tries to call zmq_connect() with any existent address which requires name resolving.

Compilation:
$ gcc -o stuck-io stuck-io.c -Wall -lzmq -lpthread

Here is the sane output:
$ ./stuck-io
[13:18:44] got a message
[13:18:45] got a message
[13:18:46] got a message
[13:18:47] got a message
[13:18:48] got a message
[13:18:49] got a message
[13:18:50] got a message

And here is the disaster if DNS server does not respond and getaddrinfo() has stuck:

$ ./stuck-io
[13:17:35] got a message
[13:17:55] got a message   <<< the whole IO processing was stuck for 20 seconds
[13:17:55] got a message   <<< now all messages are uncorked and can be processed
[13:17:55] got a message
[13:17:55] got a message
[13:17:55] got a message
[13:17:55] got a message
[13:17:55] got a message
[13:17:55] got a message

Attached source: [stuck-io.c.txt](https://github.com/zeromq/libzmq/files/2348938/stuck-io.c.txt)

--
Roman

**Comment by bluca** [comment] 2018-09-04 22:45
Duplicate of https://github.com/zeromq/libzmq/issues/2961

**Closed by bluca** 2018-09-04 22:45 UTC
