### ISSUE TITLE
error: too few arguments to function ‘getrandom’

### ISSUE THREAD

**Issue by skanskan** [zeromq/libzmq#2660] opened 2017-08-07 00:53 UTC
Hello.

When I run 

```
git clone https://github.com/zeromq/libzmq
./autogen.sh && ./configure && make -j 4
```
I get this error:
```
src/tweetnacl.c: In function ‘randombytes’:
src/tweetnacl.c:936:13: error: too few arguments to function ‘getrandom’
         i = getrandom (x, i);
             ^~~~~~~~~
In file included from src/tweetnacl.c:912:0:
/usr/include/sys/random.h:33:9: note: declared here
 ssize_t getrandom (void *__buffer, size_t __length,
         ^~~~~~~~~
make[1]: *** [Makefile:3279: src/src_libzmq_la-tweetnacl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/libzmq'
make: *** [Makefile:4078: all-recursive] Error 1

```

And I can't continue with the compilation.

I'm using OpenSUSE Tumbleweed

**Comment by bluca** [comment] 2017-08-07 07:41
Fixed by https://github.com/zeromq/libzmq/pull/2661

**Closed by bluca** 2017-08-07 07:41 UTC

**Comment by jimklimov** [comment] 2017-08-07 07:54
...and happens to be a duplicate of #2658 ;)
