### ISSUE TITLE
Calling zmq_disconnect() on a socket that was disconnected internally causes a crash

### ISSUE THREAD

**Issue by Foobarie** [zeromq/libzmq#2780] opened 2017-10-16 14:10 UTC
# Issue description

I have a PUB-SUB implementation that due to issue 1199 uses a simple heartbeat to understand if a peer had some network disruption (for example the network cable was abruptly removed) and re-add the peer in such situations. When testing using some network disruption software (in my case I've been using Clumsy), ZeroMQ notes that the connection has dropped and closes it through process_pipe_term_ack().

However, the deleted pipe is still listed in the socket's endpoint structure (socket_base_t::endpoints) and a disconnection causes an attempt to clean up the previously-deleted pipe (through the deleted pointer in endpoints) and thus generates an abort() as the pipe's status value makes no sense.

Am I missing something in how I disconnect and reconnect "dead" peers or is there no way around the issue until a fix in the library is implemented?

# Environment

* libzmq version (commit hash if unreleased): 4.1.5, 4.1.6, 4.2.2
* OS: Windows Server 2012 R2

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)
libzmq aborts the parent process.

# What's the expected result?
Process does not crash and zmq_disconnect() returns.

**Comment by bluca** [comment] 2017-10-16 14:31
Could you share code and commands to reproduce the issue?

**Comment by sigiesec** [comment] 2017-10-16 14:36
#1199 has been closed as someone assumed the problem resolved, and was never reopened, but commented on afterwards. I have not digged into the details of that issue, do you think it should be reopened?

**Comment by bluca** [comment] 2017-10-16 14:42
The issue was the lack of heartbeats, but that is now included in the library, so I don't think it's necessary to re-open it

**Comment by bluca** [comment] 2017-10-16 14:44
Perhaps the code should use send_term_endpoint to close the connection, so that it's fully de-allocated?

**Comment by bluca** [comment] 2017-10-22 17:07
@Foobarie I cannot reproduce this.

If it's as you mentioned, it should be sufficient to add ```zmq_disconnect(client, my_endpoint);``` at https://github.com/zeromq/libzmq/blob/master/tests/test_heartbeats.cpp#L272 but it works just fine.

Could you please share the code to reproduce the issue?

**Comment by bluca** [comment] 2018-03-24 10:48
No updates, closing

**Closed by bluca** 2018-03-24 10:48 UTC
Labels: Area (Runtime / Usage), Platform (windows/msvc), Symptom (Crash/Race/Undefined behavior)
