### ISSUE TITLE
ZMQ_SNDHWM and ZMQ_RCVHWM non-functional

### ISSUE THREAD

**Issue by cinchent** [zeromq/libzmq#1416] opened 2015-06-03 20:36 UTC
This is a continuation of issue #1373.  OP on that issue never really had his question answered satisfactorily, and I'm running into a similar situation.

I'm evaluating ZeroMQ to determine its suitability as the messaging backbone within a commercial surgical product.  To evaluate its lossiness and queue scalability, I took the boilerplate synchronous pub/sub example from the 0MQ site, modified it to just use single pub-single sub, set the HWM parameters explicitly, and added subscriber lossiness checking.

Ubuntu 14.04/Intel, g++ 4.8.2, 0MQ 4.1.1 stable.

Source code is here:
  Pub: http://pastebin.com/3rXPXYCk
  Sub: http://pastebin.com/XpB8TChn

All tests are with the sub side started first, then the pub side.  First test, specifying 999 messages (plus the "END" message), everything works, every time.  Specifying 1000 messages on both command lines (in which case 1001 messages are published in all), then about half the time, the END message gets lost, and the test doesn't terminate.  If it is received, though, everything runs to completion.

Now, the real problem: if I scale HWM on both sides up to increase the overall outstanding message capacity, then messages are still being lost, and that occurs after 1000 successful transfers -- not coincidentally, the default libzmq HWM value.  Here's what the subscriber outputs:

~/explore/zmq/pubsub$ ./syncsub 5000
HWM set to 5001
Synced to publisher...
Received update 100...
...
Received update 900...
Received update 1000...
ERROR: received update 3975 mismatches -- expected: 1001
Received 1001 updates

(Of course, it's a varying number of messages being dropped, 3975 in this case might be 2937 in another run.)  This observed behavior is consistent with the RCVHWM setting being at least partially ignored, and a bolus of messages being dumped into the bit bucket.  This behavior remains exactly the same regardless of what command-line parameters are specified on both sides to scale the HWM value -- all the way up to 50000!

As explained in the other problem report, I do understand that there are other variables to this queue-sizing problem -- internal buffers, etc. -- and that this is an inexact science, but it would be a reasonable expectation for a 50x increase (!) in the buffering capacity to have at least some effect on when message loss occurs, but it doesn't.

I would love to use ZeroMQ -- it's well-conceived, simple, and very practical -- but this type of deficiency is serious enough to scare me away from choosing it.

**Comment by hintjens** [comment] 2015-06-03 20:44
A reproducible minimal case in C (not C++) would be helpful in moving this
forward. Also, unless a mix of pub/sub and req/rep socket flows is
necessary to reproduce the error, can we do without that? The simpler the
better.

**Comment by cinchent** [comment] 2015-06-03 21:04
In the process of creating the C variant, I discovered what the problem was.  Changing HWM settings must occur after socket creation, of course, but *before* the bind() or connect().  Doing so after binding/connecting created this anomaly.  Apparently these are not settings that can take effect "on the fly", even on a quiescent socket.

**Comment by hintjens** [comment] 2015-06-03 21:17
Hmm... this is well documented and yet catches people out.

When I read your test cases I actually looked for that and still, missed it.

I think there's a design flaw in the API here. Not sure what the right
solution is though.

**Comment by xaqq** [comment] 2015-06-03 23:38
I am reopening this one.
I took a quick look at http://api.zeromq.org/4-1:zmq-setsockopt but I didn't find anything mentioning that the change to HWM settings must occur after socket creation and before `bind()`/`connect()`.
We need to improve the documentation for this.

Also, since it has no effect, I believe the call to `zmq_setsockopt()` should fail and returns `-1` when it is called too late (after `bind()`/`connect()`.

I'll submit a PR introducing a failing test that will check that `zmq_setsockopt()` fails.

**Comment by hintjens** [comment] 2015-06-04 04:41
The man page for zmq_setsockopt says, at the start:

    Caution: All options, with the exception of ZMQ_SUBSCRIBE, 
    ZMQ_UNSUBSCRIBE, ZMQ_LINGER, ZMQ_ROUTER_HANDOVER, 
    ZMQ_ROUTER_MANDATORY, ZMQ_PROBE_ROUTER, ZMQ_XPUB_VERBOSE, 
    ZMQ_REQ_CORRELATE, and ZMQ_REQ_RELAXED, only take effect 
    for subsequent socket bind/connects.

So this applies to many socket options, not just HWM. For example, security.

If we simply change this behavior we will break existing applications that depend on it. E.g. set HWM to one value, make a connect; set HWM to another value, call connect again.

I've opened an issue more focussed on this problem, #1420. Let's close this issue.

**Closed** 2015-06-05 20:15 UTC
