### ISSUE TITLE
zmq raise exception in I/O thread

### ISSUE THREAD

**Issue by vibk** [zeromq/libzmq#3263] opened 2018-09-28 19:05 UTC
when we send bad data into zmq socket, I/O thread raises exception and process gets killed. 

Call stack of crash is as below

00 KERNELBASE!RaiseException+0x68
01 zmq::zmq_abort(char * errmsg_ = <Value unavailable error>)+0x21 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\err.cpp @ 89]
02 zmq::tcp_read(unsigned int64 s_ = <Value unavailable error>, void * data_ = <Value unavailable error>, unsigned int64 size_ = <Value unavailable error>)+0xa9 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\tcp.cpp @ 276]
03 zmq::stream_engine_t::in_event(void)+0x132 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\stream_engine.cpp @ 318]
04 zmq::select_t::trigger_events(class std::vector<zmq::select_t::fd_entry_t,std::allocator<zmq::select_t::fd_entry_t> > * fd_entries_ = 0x0000019d`323400c8, struct zmq::select_t::fds_set_t * local_fds_set_ = 0x0000006f`e3f9fb90, int event_count_ = 0n2)+0x74 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\select.cpp @ 122]
05 zmq::select_t::select_family_entry(struct zmq::select_t::family_entry_t * family_entry_ = 0x0000019d`323400c8, int max_fd_ = 0n0, bool use_timeout_ = <Value unavailable error>, struct timeval * tv_ = 0x0000006f`e3fffc98)+0xe9 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\select.cpp @ 404]
06 zmq::select_t::loop(void)+0x352 [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\select.cpp @ 360]
07 thread_routine(void * arg_ = <Value unavailable error>)+0xd [objdir-windows-msvc-14.0.x86_64\build\libzmq\src\thread.cpp @ 47]
08 invoke_thread_procedure+0xe (Inline Function @ 00007ff7`50b99cf9) [d:\th\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 91]

Can anyone please help how to catch this exception ?

**Comment by bluca** [comment] 2018-09-29 08:49
What do you mean by "bad data"? Can you provide an example program to reproduce it?

**Comment by sigiesec** [comment] 2018-09-29 09:58
Also, which version of libzmq are you using? Can you try to use the current master and check if the issue persists?

**Comment by bluca** [comment] 2018-10-01 20:48
I cannot reproduce this on Linux. @sigiesec can you repro on Windows?

**Comment by vibk** [comment] 2018-10-01 21:16
I tested on windows.

**Comment by toonetown** [comment] 2018-10-01 22:51
I am seeing it crash on windows, I do *not* see it crash on macOS.

I used the following files:

### server.py ###
```
import zmq
import time

port = "5556"
           
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:%s" % port)

while True:
    #  Wait for next request from client
    message = socket.recv()
    print ("Received request: ", message)
    time.sleep (1) 
    socket.send_string("World from %s" % port)
```

### client.py ###
```
import zmq
import socket
 
port = 5556

buf = b"\xff\x00\x00\x00\x00\xf3\xa0\x81\x8d\x00"
#crash
print ("Connecting to server...")
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("localhost", int(port)))
s.send(buf)
data = s.recv(256)
s.close()
print("received data:" + str(data))
```

**Comment by sigiesec** [comment] 2018-10-02 06:03
@vibk 4.2.3 is neither the latest release, which is rather 4.2.5, nor the master version. Which one are you using? In case of an unreleased version, please provide the commit SHA.

**Comment by toonetown** [comment] 2018-10-02 12:07
@sigiesec http://zeromq.org/intro:get-the-software lists the latest stable version as 4.2.3. However, I was seeing the same when using they python scripts posted above using version 17.1.2 of the python bindings (which, appear to be using 4.2.5). 

Also - I only see the crash (again, with the python scripts) on Windows - not on macOS or Linux.

**Comment by bluca** [comment] 2018-10-02 12:17
I have updated that wiki page, it's not done automatically and we forgot last time

**Comment by toonetown** [comment] 2018-10-02 14:55
OK - I've run a couple of tests and am getting the crash using ZMQ 4.2.5 (Windows only).

You can crash the server every time (I am just using the "Hello World" server from the guide): http://zguide.zeromq.org/cpp:hwserver

To crash the server, you can run the following python script (requires Python 3):

### crash-server.py ###
```
import socket
 
buf = b"\xff\x00\x00\x00\x00\xf3\xa0\x81\x8d\x00"
#crash
print ("Connecting to server...")
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("localhost", 5555))
s.send(buf)
data = s.recv(256)
s.close()
print("received data:" + data.hex())
```

**NOTE:** that the python script is *not* using ZMQ...it is just sending junk data to the port that ZMQ has opened.  This is (I believe) the issue...that ZMQ is not handling misformatted data that might get sent to it.

Again - this appears to be windows-only (when the server is running on Windows).  I have not been able to reproduce with a server running on macOS or Linux.

**Comment by bluca** [comment] 2018-10-02 15:05
> This is (I believe) the issue...that ZMQ is not handling misformatted data that might get sent to it.

I don't think so. I think the issue is simply the tcp read buffer size of Windows. But some Windows developer needs to look into it.

**Comment by peterdjalaliev** [comment] 2018-10-25 21:56
Hello, has anybody been able to investigate this?
Regards, Peter

**Comment by opedroso** [comment] 2018-11-02 08:05
I'll take a look at it sometime this weekend.

**Comment by opedroso** [comment] 2018-11-04 05:39
I used LIBZMQ 4.2.5 source zip and built it using VS Studio 17 Community Edition.
I used the client/server from toonetown post above (which I download to client2.py and server2.py).
I cannot reproduce the problem.
If anybody can, please let me know steps to reproduce it.

'''
C:\Users\opedroso\source\repos\client>python client2.py
Connecting to server...
received data:b'\xff\x00\x00\x00\x00\x00\x00\x00\x01\x7f'
'''

**Comment by bluca** [comment] 2018-11-04 10:30
Thanks for checking.

Could it be a mis configuration of the OS? Unrealistically small buffers set by default? Is that a thing that can be done on Windows?

**Comment by toonetown** [comment] 2018-11-04 14:58
I was seeing the crash when using the `crash-server.py` script to crash the server, but just using the hello-world c++ example. The example I built using the statically-built version of zeromq built with vs2017.

**Comment by toonetown** [comment] 2018-11-04 15:00
One other note: when I was seeing the crash using the `server.py` script previously posted, I was just using the version of zeromq that got installed using `pip`.

**Comment by opedroso** [comment] 2018-11-04 19:49
How did you install ZMQ using pip?

**Comment by toonetown** [comment] 2018-11-04 19:55
I just ran `pip install pyzmq`. But the reason I tried reproducing with actual zeromq (compiled from source to a static library) was to eliminate the possibility that it was pyzmq-related.  

I was able to reproduce using the statically-compiled library, too (as outlined in my last comment from Oct 2nd).

**Comment by toonetown** [comment] 2018-11-04 20:00
If it might be easier to work on this via email, feel free to reach out to me at <myfirstname>_<my last name> at symantec dot com.

**Comment by toonetown** [comment] 2018-11-05 23:02
It appears that this might be due to the fact that on windows, the `recv` call is returning `WSAENOBUFS`.  Allowing that to be a "valid" error in the assert statement in `tcp_read` (tcp.cpp:267) seems to fix the issue.

According to the documentation at https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv, it doesn't explicitly stat that `recv` can return `WSAENOBUFS`, but it appears that's what's being returned in this particular case.

**Comment by toonetown** [comment] 2018-11-05 23:08
Perhaps, this might be related to the issue described at https://zeromq.jira.com/browse/LIBZMQ-195 (I found that reference in the code for `tcp_write` - where it actually *does* handle `WSAENOBUFS`.

**Comment by bluca** [comment] 2018-11-05 23:09
On which version of Windows do you see this error?

**Comment by toonetown** [comment] 2018-11-05 23:11
Windows 10.

I'm actually putting up a PR so it can be more easily-reviewed.  Feel free to reject it or to totally hack it apart (it's a simple proposed change...but, admittedly, I don't know all the ramifications that it may trigger)

**Comment by bluca** [comment] 2018-11-05 23:14
It's weird because the examples you posted definitely don't have large buffers. Are you sure your OS is not configured in some strange and broken way? Can these buffers sizes be controlled by the user like on *nix?

**Comment by toonetown** [comment] 2018-11-05 23:18
I don't know all the steps in the code that least to this state, but in the example I posted, it actually leads to calling `tcp_read` with a buffer size of 4087382412.  In https://github.com/zeromq/libzmq/blob/master/src/stream_engine.cpp#L313 the call to `get_buffer` sets the value of `buffsize` to that.  (Verified by setting breakpoints and inspecting variables in the VS debugger...as mentioned, I don't know all the things that might be leading to that state)

**Comment by bluca** [comment] 2018-11-05 23:21
That is... not good.

**Comment by toonetown** [comment] 2018-11-05 23:29
Perhaps it's relying on the operating system to enforce the size...given the comment in the code in that same place?

```
//  Retrieve the buffer and read as much data as possible.
//  Note that buffer can be arbitrarily large. However, we assume
//  the underlying TCP layer has fixed buffer size and thus the
//  number of bytes read will be always limited.
```

It appears that windows is *ok* with sending the buffer too big...it just errors out (and zmq is not handling the error code).  However, maybe there's a bigger issue?

**Comment by toonetown** [comment] 2018-11-05 23:38
I have validated that on macOS at least, the size of `buff size` in stream_engine.cpp:313 is *also* set to 4087382412 when running this example python script.  In that case, however, `tcp_read` is just returning `-1` instead of asserting, as in the windows case.

**Comment by bluca** [comment] 2018-11-06 00:42
So the data the example is sending is being interpreted as a v1 message, as that's what the first bytes look like. At some point then 4087382413 is read as the message size, which is happily used as ZMQ_MAX_MSG_SIZE is not set, and that's where it comes from. I think you fix is correct.

**Comment by sigiesec** [comment] 2018-11-06 09:53
What I find somewhat startling is that the allocation for 4087382413 bytes apparently succeeds. Shouldn't this fail in zmq::v1_decoder_t::eight_byte_size_ready and return ENOMEM? Then we would never get to tcp_read with that size.

**Comment by bluca** [comment] 2018-11-06 09:56
The wonders of modern virtual memory I suppose. At least on Linux, I believe until you actually try to use it it's not _really_ allocated.

**Comment by opedroso** [comment] 2018-11-06 10:17
Maybe not really allocated physically, but the process virtual range must
have been extended such that malloc will be able to return the pointer.
Page Table Entries have to be created for that address even if they are not
yet backed by an actual page (or disk block) yet.

And because the way malloc data structures are (control data lives in
between allocations in Windows), that means that most likely both ends of
the buffer will actually be committed as well (once again in Windows).
Oops, the above statement is only true for allocations smaller than ~511Kb
in Windows.
For larger allocations, a VirtualAlloc() is done (sort of sbrk()
equivalent) and the pointer returned is then managed by the malloc code.
When free() is called with the malloc returned pointer, VirtualFree() will
be called on that pointer and the memory actually gets removed from your
process space.

Remember this is running in 64 bits. If I am not mistaken, Windows
currently can extend a process all the way to 7 Tb, obviously depending on
other settings like automatic pagefile mgmt being on (the default).
Extending the pagefile for ~4 Gb on today's disk systems won't be a
problem, given there is enough free disk on pagefile where disk is located.

Has anybody checked if that allocation actually successfully completes in
Linux?
If that fails, the return would still be -1 and it would explain the
different behavior in Windows/Linux.

Now, I followed the steps Nathan provided me to reproduce it and I still
cannot reproduce this problem.
For me the, I can run the crash-server.py multiple times and it receives
the binary string sent every time without a problem.

**Comment by bluca** [comment] 2018-11-06 10:38
Fixed by https://github.com/zeromq/libzmq/pull/3297

**Comment by bluca** [comment] 2018-11-06 10:39
> Has anybody checked if that allocation actually successfully completes in
Linux?

Yes I have, it completes just fine, the difference is the error returned from the read syscall

**Closed by bluca** 2018-11-06 10:38 UTC
Labels: Area (Runtime / Usage), Platform (windows/msvc), Problem reproduced
