### ISSUE TITLE
socket Identity bug

### ISSUE THREAD

**Issue by githubChrys** [zeromq/libzmq#856] opened 2014-01-26 15:35 UTC
Hello,

I think I found a bug with ZeroMQ regarding identities in zmq 4.0.1 
(I am using the C++ bindings)

I have setup the following topology in my network layer:

REQ -> ROUTER(1) DEALER --> ROUTER(2)

the ROUTER(1) and DEALER are both Bound.
REQ is connected to ROUTER(1) 
ROUTER(2) is connected to DEALER

ROUTER(1) and DEALER are connected via a zmq proxy.

It seems that if I set the identity of REQ to something like   "sampreq"
then if I set the DEALER identity i.e. to "DEAL" then on ROUTER(2)
the identity I receive is going to be "DEALreq"
if I set the DEALER identity i.e. to "myDEAL" then on ROUTER(2) 
the identity I receive is going to be myDEALq"
I also tried to set identities larger than 7 characters, i.e. setting the 
DEALER identity to "myDEALERisAwesome" which would result in
ROUTER(2) receiving an identity that looks something like this
"myDEALERisAwesometcp//10.0.0122:4005ÍÍÍÍÍÍÍÍÍÍÍÍÍÍ\x11\e\x1ÍÍÍÍÍÍÍ" (etc...)

to me it looks like if the identity string is larger than 7 characters then some corrupt memory is being appended to the forwarded identity.
also if the identity string of the second socket (in my case the DEALER) then the forwarded identity is filled with the characters contained in the previous sockets identity (in my case the REQ).

I tried to step into the setsockopt function to see what the limits of the identity were and it seems like any identity of up to 255 characters should be fine. I then checked what the proxy was receiving on the the front end and the REQ identity was already screwed up. Which leads me to believe that the Router is somehow bugged in how it forwards the identity of the REQ  and  in the case of ROUTER(2) how it forwards the DEALERs identity.

I will try figure out more but I am fairly new to ZeroMQ. In the meantime maybe some more experienced zmq developer can take a look.

**Comment by bluca** [comment] 2017-01-03 10:50
Closing as this was caused by a problem in the example

**Closed by bluca** 2017-01-03 10:50 UTC
