### ISSUE TITLE
Warnings on OpenBSD

### ISSUE THREAD

**Issue by mosconi** [zeromq/libzmq#940] opened 2014-03-19 23:47 UTC
During the build on zeromq 4.0.4, some wanings are generated:
```
.libs/libzmq.so.4.0: warning: tempnam() possibly used unsafely; consider using mkstemp()
.libs/libzmq.so.4.0: warning: strcpy() is almost always misused, please use strlcpy()
.libs/libzmq.so.4.0: warning: rand() isn't random; consider using arc4random()
.libs/libzmq.so.4.0: warning: srand() seed choices are invariably poor
```

**Comment by kYroL01** [comment] 2015-08-16 09:59
I see the problem is fixed. You can close the issue.

**Closed** 2015-08-16 10:01 UTC
