### ISSUE TITLE
inproc issue with: zmq_bind() and zmq_unbind()

### ISSUE THREAD

**Issue by horus42** [zeromq/libzmq#918] opened 2014-03-12 13:54 UTC
Sample code:
zmq_bind( s, "inproc://XXX" );
zmq_unbind( s, "inproc://XXX" );

Issue: 
unbind will tell that the given inproc doesn't actually exist. This error is originating from socket_base.cpp:718. The inproc member variable does not contain the bound address. Size of the inproc container is 0.

Is this a bug or working as intended?

**Comment by calid** [comment] 2015-03-15 14:13
@hintjens @hurtonm probably can close this as a duplicate of #949

**Comment by hintjens** [comment] 2015-03-15 16:02
OK, closing as duplicate.

**Closed by hintjens** 2015-03-15 16:02 UTC
