### ISSUE TITLE
Warnings for gss deprecated functions on OS X

### ISSUE THREAD

**Issue by dmeehan1968** [zeromq/libzmq#1039] opened 2014-05-16 11:12 UTC
Building from latest master.

```
make
```
produces

```
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CXX      libzmq_la-clock.lo
  CXX      libzmq_la-curve_client.lo
  CXX      libzmq_la-address.lo
  CXX      libzmq_la-ctx.lo
  CXX      libzmq_la-curve_server.lo
  CXX      libzmq_la-devpoll.lo
  CXX      libzmq_la-dist.lo
  CXX      libzmq_la-epoll.lo
  CXX      libzmq_la-err.lo
  CXX      libzmq_la-fq.lo
  CXX      libzmq_la-gssapi_mechanism_base.lo
  CXX      libzmq_la-gssapi_client.lo
gssapi_mechanism_base.cpp:58:9: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_name(&min_stat, &target_name);
        ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_mechanism_base.cpp:60:9: warning: 'gss_delete_sec_context' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
        gss_delete_sec_context(&min_stat, &context, GSS_C_NO_BUFFER);
        ^
/usr/include/gssapi/gssapi.h:498:1: note: 'gss_delete_sec_context' declared here
gss_delete_sec_context(
^
gssapi_mechanism_base.cpp:81:16: warning: 'gss_wrap' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    maj_stat = gss_wrap(&min_stat, context, 1, GSS_C_QOP_DEFAULT,
               ^
/usr/include/gssapi/gssapi.h:532:1: note: 'gss_wrap' declared here
gss_wrap(
^
gssapi_mechanism_base.cpp:108:5: warning: 'gss_release_buffer' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    gss_release_buffer (&min_stat, &wrapped);
    ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_mechanism_base.cpp:154:16: warning: 'gss_unwrap' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    maj_stat = gss_unwrap(&min_stat, context, &wrapped, &plaintext,
               ^
/usr/include/gssapi/gssapi.h:544:1: note: 'gss_unwrap' declared here
gss_unwrap(
^
gssapi_mechanism_base.cpp:173:5: warning: 'gss_release_buffer' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    gss_release_buffer (&min_stat, &plaintext);
    ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_mechanism_base.cpp:174:5: warning: 'gss_release_buffer' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    gss_release_buffer (&min_stat, &wrapped);
    ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_mechanism_base.cpp:319:16: warning: 'gss_import_name' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    maj_stat = gss_import_name (&min_stat, &name_buf,
               ^
/usr/include/gssapi/gssapi.h:586:1: note: 'gss_import_name' declared here
gss_import_name(
^
gssapi_mechanism_base.cpp:325:16: warning: 'gss_acquire_cred' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    maj_stat = gss_acquire_cred (&min_stat, server_name, 0,
               ^
/usr/include/gssapi/gssapi.h:445:1: note: 'gss_acquire_cred' declared here
gss_acquire_cred(
^
gssapi_mechanism_base.cpp:332:5: warning: 'gss_release_name' is deprecated: use GSS.framework
      [-Wdeprecated-declarations]
    gss_release_name(&min_stat, &server_name);
    ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
10 warnings generated.
  CXX      libzmq_la-gssapi_server.lo
gssapi_client.cpp:70:9: warning: 'gss_release_cred' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_cred(&min_stat, &cred);
        ^
/usr/include/gssapi/gssapi.h:456:1: note: 'gss_release_cred' declared here
gss_release_cred(
^
gssapi_client.cpp:167:25: warning: 'gss_import_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        OM_uint32 maj = gss_import_name(&min_stat, &send_tok,
                        ^
/usr/include/gssapi/gssapi.h:586:1: note: 'gss_import_name' declared here
gss_import_name(
^
gssapi_client.cpp:175:16: warning: 'gss_init_sec_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    maj_stat = gss_init_sec_context(&init_sec_min_stat, cred, &context,
               ^
/usr/include/gssapi/gssapi.h:461:1: note: 'gss_init_sec_context' declared here
gss_init_sec_context(
^
gssapi_client.cpp:190:13: warning: 'gss_release_buffer' is deprecated: use GSS.framework [-Wdeprecated-declarations]
            gss_release_buffer(&min_stat, &send_tok);
            ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_client.cpp:191:13: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
            gss_release_name(&min_stat, &target_name);
            ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_client.cpp:195:5: warning: 'gss_release_buffer' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    gss_release_buffer(&min_stat, &send_tok);
    ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_client.cpp:198:9: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_name(&min_stat, &target_name);
        ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_client.cpp:200:13: warning: 'gss_delete_sec_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
            gss_delete_sec_context(&min_stat, &context, GSS_C_NO_BUFFER);
            ^
/usr/include/gssapi/gssapi.h:498:1: note: 'gss_delete_sec_context' declared here
gss_delete_sec_context(
^
gssapi_client.cpp:211:13: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
            gss_release_name(&min_stat, &target_name);
            ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
9 warnings generated.
  CXX      libzmq_la-io_object.lo
  CXX      libzmq_la-io_thread.lo
gssapi_server.cpp:64:9: warning: 'gss_release_cred' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_cred(&min_stat, &cred);
        ^
/usr/include/gssapi/gssapi.h:456:1: note: 'gss_release_cred' declared here
gss_release_cred(
^
gssapi_server.cpp:67:9: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_name(&min_stat, &target_name);
        ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_server.cpp:206:5: warning: 'gss_display_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    gss_display_name(&min_stat, target_name, &principal, NULL);
    ^
/usr/include/gssapi/gssapi.h:578:1: note: 'gss_display_name' declared here
gss_display_name(
^
gssapi_server.cpp:213:5: warning: 'gss_release_buffer' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    gss_release_buffer(&min_stat, &principal);
    ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_server.cpp:328:9: warning: 'gss_release_buffer' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_buffer(&min_stat, &send_tok);
        ^
/usr/include/gssapi/gssapi.h:598:1: note: 'gss_release_buffer' declared here
gss_release_buffer(
^
gssapi_server.cpp:332:9: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        gss_release_name(&min_stat, &target_name);
        ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_server.cpp:334:13: warning: 'gss_delete_sec_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
            gss_delete_sec_context(&min_stat, &context, GSS_C_NO_BUFFER);
            ^
/usr/include/gssapi/gssapi.h:498:1: note: 'gss_delete_sec_context' declared here
gss_delete_sec_context(
^
gssapi_server.cpp:346:17: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
                gss_release_name(&min_stat, &target_name);
                ^
/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' declared here
gss_release_name(
^
gssapi_server.cpp:356:16: warning: 'gss_accept_sec_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    maj_stat = gss_accept_sec_context(&init_sec_min_stat, &context, cred,
               ^
/usr/include/gssapi/gssapi.h:477:1: note: 'gss_accept_sec_context' declared here
gss_accept_sec_context(
^
  CXX      libzmq_la-ip.lo
9 warnings generated.
  CXX      libzmq_la-ipc_address.lo
  CXX      libzmq_la-ipc_connecter.lo
  CXX      libzmq_la-ipc_listener.lo
  CXX      libzmq_la-kqueue.lo
  CXX      libzmq_la-lb.lo
  CXX      libzmq_la-mailbox.lo
  CXX      libzmq_la-mechanism.lo
  CXX      libzmq_la-metadata.lo
  CXX      libzmq_la-msg.lo
  CXX      libzmq_la-mtrie.lo
  CXX      libzmq_la-norm_engine.lo
  CXX      libzmq_la-null_mechanism.lo
  CXX      libzmq_la-object.lo
  CXX      libzmq_la-options.lo
  CXX      libzmq_la-own.lo
  CXX      libzmq_la-pair.lo
  CXX      libzmq_la-pgm_receiver.lo
  CXX      libzmq_la-pgm_sender.lo
  CXX      libzmq_la-pgm_socket.lo
  CXX      libzmq_la-pipe.lo
  CXX      libzmq_la-plain_client.lo
  CXX      libzmq_la-plain_server.lo
  CXX      libzmq_la-poll.lo
  CXX      libzmq_la-poller_base.lo
  CXX      libzmq_la-pull.lo
  CXX      libzmq_la-push.lo
  CXX      libzmq_la-proxy.lo
  CXX      libzmq_la-reaper.lo
  CXX      libzmq_la-pub.lo
  CXX      libzmq_la-random.lo
  CXX      libzmq_la-rep.lo
  CXX      libzmq_la-req.lo
  CXX      libzmq_la-select.lo
  CXX      libzmq_la-session_base.lo
  CXX      libzmq_la-signaler.lo
  CXX      libzmq_la-socket_base.lo
  CXX      libzmq_la-stream.lo
  CXX      libzmq_la-stream_engine.lo
  CXX      libzmq_la-sub.lo
  CXX      libzmq_la-tcp.lo
  CXX      libzmq_la-tcp_address.lo
  CXX      libzmq_la-tcp_connecter.lo
  CXX      libzmq_la-tcp_listener.lo
  CXX      libzmq_la-thread.lo
  CXX      libzmq_la-trie.lo
  CXX      libzmq_la-xpub.lo
  CXX      libzmq_la-router.lo
  CXX      libzmq_la-dealer.lo
  CXX      libzmq_la-v1_decoder.lo
  CXX      libzmq_la-v1_encoder.lo
  CXX      libzmq_la-v2_decoder.lo
  CXX      libzmq_la-v2_encoder.lo
  CXX      libzmq_la-xsub.lo
  CXX      libzmq_la-zmq.lo
  CXX      libzmq_la-zmq_utils.lo
  CXX      libzmq_la-raw_decoder.lo
  CXX      libzmq_la-raw_encoder.lo
  CXX      libzmq_la-tipc_address.lo
  CXX      libzmq_la-tipc_listener.lo
  CXX      libzmq_la-tipc_connecter.lo
  CXXLD    libzmq.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-devpoll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-epoll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-norm_engine.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_receiver.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_sender.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_socket.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-poll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-select.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_address.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_listener.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_connecter.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-devpoll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-epoll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-norm_engine.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_receiver.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_sender.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-pgm_socket.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-poll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-select.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_address.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_listener.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libzmq.a(libzmq_la-tipc_connecter.o) has no symbols
Making all in doc
make[1]: Nothing to be done for `all'.
Making all in perf
  CXX      local_lat.o
  CXX      local_thr.o
  CXX      remote_lat.o
  CXX      remote_thr.o
  CXX      inproc_lat.o
  CXX      inproc_thr.o
  CXXLD    local_lat
  CXXLD    remote_lat
  CXXLD    local_thr
  CXXLD    remote_thr
  CXXLD    inproc_lat
  CXXLD    inproc_thr
Making all in tests
  CXX      test_system.o
  CXX      test_pair_inproc.o
  CXX      test_pair_tcp.o
  CXX      test_reqrep_inproc.o
  CXX      test_reqrep_tcp.o
  CXX      test_hwm.o
  CXX      test_reqrep_device.o
  CXX      test_sub_forward.o
  CXX      test_msg_flags.o
  CXX      test_invalid_rep.o
  CXX      test_connect_resolve.o
  CXX      test_immediate.o
  CXX      test_last_endpoint.o
  CXX      test_term_endpoint.o
  CXX      test_srcfd.o
  CXX      test_monitor.o
  CXX      test_router_mandatory.o
  CXX      test_router_handover.o
  CXX      test_probe_router.o
  CXX      test_stream.o
  CXX      test_stream_empty.o
  CXX      test_stream_disconnect.o
  CXX      test_stream_timeout.o
  CXX      test_disconnect_inproc.o
  CXX      test_ctx_options.o
  CXX      test_ctx_destroy.o
  CXX      test_security_null.o
  CXX      test_security_plain.o
  CXX      test_security_curve.o
  CXX      test_iov.o
  CXX      test_spec_req.o
  CXX      test_spec_rep.o
  CXX      test_spec_dealer.o
  CXX      test_spec_router.o
  CXX      test_spec_pushpull.o
  CXX      test_req_correlate.o
  CXX      test_req_relaxed.o
  CXX      test_conflate.o
  CXX      test_inproc_connect.o
  CXX      test_issue_566.o
  CXX      test_proxy.o
  CXX      test_abstract_ipc.o
  CXX      test_many_sockets.o
  CXX      test_ipc_wildcard.o
  CXX      test_diffserv.o
  CXX      test_connect_rid.o
  CXX      test_bind_src_address.o
  CXX      test_metadata.o
  CXX      test_id2fd.o
  CXX      test_shutdown_stress.o
  CXX      test_pair_ipc.o
  CXX      test_reqrep_ipc.o
  CXX      test_timeo.o
  CXX      test_filter_ipc.o
  CXX      test_fork.o
  CXXLD    test_system
  CXXLD    test_pair_inproc
  CXXLD    test_pair_tcp
  CXXLD    test_reqrep_inproc
  CXXLD    test_reqrep_tcp
  CXXLD    test_hwm
  CXXLD    test_reqrep_device
  CXXLD    test_sub_forward
  CXXLD    test_invalid_rep
  CXXLD    test_msg_flags
  CXXLD    test_connect_resolve
  CXXLD    test_immediate
  CXXLD    test_term_endpoint
  CXXLD    test_last_endpoint
  CXXLD    test_srcfd
  CXXLD    test_monitor
  CXXLD    test_router_mandatory
  CXXLD    test_router_handover
  CXXLD    test_probe_router
  CXXLD    test_stream
  CXXLD    test_stream_empty
  CXXLD    test_stream_disconnect
  CXXLD    test_stream_timeout
  CXXLD    test_disconnect_inproc
  CXXLD    test_ctx_options
  CXXLD    test_ctx_destroy
  CXXLD    test_security_null
  CXXLD    test_security_plain
  CXXLD    test_security_curve
  CXXLD    test_iov
  CXXLD    test_spec_req
  CXXLD    test_spec_dealer
  CXXLD    test_spec_rep
  CXXLD    test_spec_router
  CXXLD    test_spec_pushpull
  CXXLD    test_req_correlate
  CXXLD    test_req_relaxed
  CXXLD    test_conflate
  CXXLD    test_inproc_connect
  CXXLD    test_issue_566
  CXXLD    test_proxy
  CXXLD    test_abstract_ipc
  CXXLD    test_many_sockets
  CXXLD    test_ipc_wildcard
  CXXLD    test_diffserv
  CXXLD    test_connect_rid
  CXXLD    test_bind_src_address
  CXXLD    test_metadata
  CXXLD    test_id2fd
  CXXLD    test_shutdown_stress
  CXXLD    test_pair_ipc
  CXXLD    test_reqrep_ipc
  CXXLD    test_timeo
  CXXLD    test_filter_ipc
  CXXLD    test_fork
Making all in tools
  CXX      curve_keygen.o
  CXXLD    curve_keygen
make[1]: Nothing to be done for `all-am'.
```

**Comment by hitstergtd** [comment] 2016-04-30 21:30
@dmeehan1968, @c-rack 
I am closing the issue as I am not able to reproduce this issue on OS X El Capitan and haven't seen it turn up in the Travis CI builds either.

@dmeehan1968 
If you are still able to reproduce it then let us know and I will re-open the issue.

**Closed by hitstergtd** 2016-04-30 21:30 UTC
Labels: Build Problem, Platform (osx)
