### ISSUE TITLE
Messages are not sent if socket is closed immediately

### ISSUE THREAD

**Issue by kyllingstad** [zeromq/libzmq#1264] opened 2014-11-25 12:37 UTC
It appears that messages do not get sent if `zmq_close()` is called immediately after `zmq_send()`, even when the linger period is left at the default of "infinite". This seems contrary to [the documentation](http://api.zeromq.org/4-0:zmq-ctx-term), which says:

> After interrupting all blocking calls, `zmq_ctx_term()` shall block until [...] all messages sent by the application with `zmq_send()` have either been physically transferred to a network peer, or the socket's linger period set with the `ZMQ_LINGER` socket option has expired.

Here is a program which demonstrates the issue:

``` c
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "zmq.h"

int main(int argc, char** argv)
{
    void* ctx = zmq_ctx_new();
    assert(ctx);
    if (argc > 1) {
        // Send message
        void* sck = zmq_socket(ctx, ZMQ_DEALER);
        assert(sck);
        int rc = zmq_connect(sck, "tcp://localhost:59999");
        assert(rc == 0);
        int len = zmq_send(sck, argv[1], strlen(argv[1]), 0);
        assert(len >= 0);
        zmq_close(sck);
    } else {
        // Receive messages
        void* sck = zmq_socket(ctx, ZMQ_DEALER);
        assert(sck);
        int rc = zmq_bind(sck, "tcp://*:59999");
        assert(rc == 0);
        char buf[256];
        do {
            int len = zmq_recv(sck, &buf, 256, 0);
            assert(len >= 0 && len < 256);
            buf[len] = '\0';
            printf("%s\n", buf);
        } while (buf[0] != 'q');
        zmq_close(sck);
    }
    zmq_ctx_term(ctx);
    return 0;
}
```

Run the program without any arguments in one terminal, and with a single argument in another, and observe that nothing happens. However, if a wait (either for a certain time period or a user keypress) is inserted after `zmq_send()` and before the subsequent `zmq_close()` call, it works as expected (i.e., the messages get printed on the receiving end).

Tested with both ØMQ 4.0.4 and `libzmq` master branch (2015-06-09), using Visual Studio 2010 and 2013, on Windows 7.

**Comment by lglayal** [comment] 2015-01-21 08:07
Hello, same problem using zeromq 3.2.4 on linux CentOS 6.6, Changing LINGER values (to -1,0,1,100) has no effect. Setting ZMMQ_SNDHWM to 1 before sending the last message has no effect. The only  'workaround' I found working is to add an usleep(100000) between zmq_send() and zmq_close().
I modified your test example to send 4 messages and all messages are lost without usleep().
A tcpdump shows there is no message sent to peer, all messages seem to be stuck on client side.
Your example is using tcp endpoints, we have more complex code using inproc, ipcs and tcp endpoints, using DEALER/ROUTER pattern but with the same problem, messages are lost on zmq_close.

**Comment by pauceano** [comment] 2015-03-23 13:17
Any news about this issue? I have same problem in 4.0.5

**Comment by lglayal** [comment] 2015-04-22 14:10
Hello, for information (someone may find it usefull), we had a problem this morning, still with messages lost but with increased probability depending on CPU topology in VM guests on VMWare.
- one guest running 8 VCPU, using 1 socket with 8 cores
- one guest running 8 VCPU, using 8 sockets with one core each : this configuration shows more messages lost than previous one.

Communication occurs between 2 threads using inproc.OS is a linux x86_64, Centos 6.6 using CFS kernel scheduler with default settings.

**Comment by kyllingstad** [comment] 2015-06-09 12:23
The bug exists for Visual Studio 2013 too. (I just tested with the current libzmq master.)

**Comment by sorenh** [comment] 2015-08-06 20:44
I believe I've solved this with PR #1511. Can you please check with current master?

**Comment by kyllingstad** [comment] 2015-08-09 16:07
@sorenh:
> I believe I've solved this with PR #1511. Can you please check with current master?

I checked just now, and unfortunately, the problem persists.

**Comment by sorenh** [comment] 2015-08-09 16:20
@kyllingstad which platform did you test it on? Are you using the script from the bug description to test it?

**Comment by kyllingstad** [comment] 2015-08-09 16:58
Visual Studio 2013 on Windows 7. I am using the same code, yes.

**Comment by thehesiod** [comment] 2016-04-24 10:18
Check fix in https://github.com/zeromq/libzmq/issues/919  however it seems the fix was not complete

**Comment by hitstergtd** [comment] 2016-04-24 14:56
@kyllingstad, @thehesiod - I believe I have reproduced the issue using the test case in this PR, though I merged into one single program. Still seems to happen.

**Comment by thehesiod** [comment] 2016-04-25 03:26
see #1922 for my testcase as well.  It's python but I'm sure it's a core bug.  Kinda strange how OSX doesn't seem to be affected.  Perhaps due to a different default for SNDBUF.

**Comment by thehesiod** [comment] 2016-08-23 00:34
any way we can vote this up?  the workarounds are really bad, thanks!

**Comment by thehesiod** [comment] 2016-10-11 00:55
given this may be related to SNDBUF I'm linking this bug (https://github.com/zeromq/libzmq/issues/1922) which did a lot of digging into the default sizes across various platforms.

**Comment by omaralvarez** [comment] 2017-05-08 17:36
Same issue here, Debian 8 with 4.0.5, large messages are not sent if socket is closed quickly. I have double checked LINGER value is -1, is just being ignored.

**Comment by garnier-quentin** [comment] 2017-05-31 09:21
I have the same issue in centos 6.9 and ZMQ 3.1.19. That's really annoying. I have to add a sleep before the close. Otherwise, my other process cannot get the data. It's really simple, i have:
* one router (process stay alive)
* some dealers (process send one message (300KB) and the process exited).

I have set the LINGER to 30 seconds but it seems it doesn't work.

**Comment by bluca** [comment] 2017-05-31 09:28
Those versions are quite old, could you please try with 4.2 and see if you still have issues?

**Comment by garnier-quentin** [comment] 2017-05-31 09:35
I would like to upgrade but i don't find perl binding for zmq4 maintained.

**Comment by bluca** [comment] 2017-05-31 09:49
I use https://github.com/lestrrat/p5-ZMQ and it's just fine
API level is still 3 so it's compatible

**Comment by bluca** [comment] 2017-05-31 09:50
There's also this one but I haven't tried it: https://packages.debian.org/stretch/libzmq-ffi-perl

**Comment by garnier-quentin** [comment] 2017-05-31 09:56
Thanks. I'll tried the binding.

**Comment by garnier-quentin** [comment] 2017-05-31 10:57
I have tested with zmq 4.2.1 and it's ok

**Comment by bluca** [comment] 2017-05-31 10:59
Ok, great, thanks for confirming

@omaralvarez please let us know if 4.2 solves it for you as well - FYI you can get debian 8 packages from our OBS project: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_8.0/

**Comment by sigiesec** [comment] 2018-08-17 09:38
Since there was no activity in the last year, I assume this is resolved now.
Feel free to reopen if the problem persists.

**Closed by sigiesec** 2018-08-17 09:38 UTC
Labels: Area (Runtime / Usage), Platform (linux/generic), Platform (osx), Platform (windows/msvc), Request For Comments, Symptom (Unexpected behavior)

**Comment by thehesiod** [comment] 2018-08-17 19:51
probably a dup of this anyways: https://github.com/zeromq/libzmq/issues/1922

**Comment by bajaj689** [comment] 2019-06-24 13:15
Guys,This might help someone. I had faced the same issue in version 4.x.x . ZeroMQ has a socket option by the name ZMQ_SNDHWM. Its default value is 1000. I was testing with load of around 500-900 publisher requests on zeromq subscriber daemon. Publisher socket drops a message if the threshold is reached ( default 1000 ) .After I changed the value to 2000 and above, no messages dropped.
