### ISSUE TITLE
How can we transform **cleanly** a communication based on HTTP API --> to a message communication   using ZMQ library ?

### ISSUE THREAD

**Issue by smaillns** [zeromq/libzmq#3583] opened 2019-07-15 15:28 UTC

**Comment by bluca** [comment] 2019-07-15 19:43
Right now there's the ZMQ_STREAM socket type that allows you to talk to a plain TCP server - websocket support is being worked on, see https://github.com/zeromq/libzmq/pull/3579

**Comment by bluca** [comment] 2019-07-15 20:44
duplicate of https://github.com/zeromq/libzmq/issues/3581

**Closed by bluca** 2019-07-15 20:44 UTC

**Comment by smaillns** [comment] 2019-07-16 07:13
What about req/rep socket ? can we use ZMQ socket to carry http request ?

**Comment by somdoron** [comment] 2019-07-16 08:59
@smaillns not at the moment.
The websocket transport will be merged soon and you will be able to use that.

I'm thinking of implementing HTTP, but it will take some time.

**Comment by smaillns** [comment] 2019-07-17 07:19
Have any one comments or an idea about how to implement this example [https://github.com/smaillns/ZMQ_Samples/blob/master/capture.png](url)

**Comment by smaillns** [comment] 2019-07-17 09:28
I have another serious question.. can we customise **any** application to use ZeroMQ sockets. i.e make it **generic** as possible. 
Or let's say it differently .. can we imagine a communication layer based on ZMQ messaging system which can be adopted by any application ?
