### ISSUE TITLE
UDP dish socket can't bind to a multicast port already in use

### ISSUE THREAD

**Issue by Mystfit** [zeromq/libzmq#3236] opened 2018-08-29 10:32 UTC
# Issue description

If I bind a UDP dish socket to a multicast address that is already bound in another running program instance I get hit an "address in use" error. Tracing down the initialisation of the socket in udp_engine.cpp I found that the socket has SO_REUSEADDR set by default which sounds correct but still results in this issue.

The socket will bind if I add a SO_REUSEPORT flag immediately after like the following (this is from [udp_engine.cpp](https://github.com/zeromq/libzmq/blob/50dbd80c515e31afda2193bd0b875aa31b7c9059/src/udp_engine.cpp#L194))

```
int rc = setsockopt (_fd, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<char *> (&on), sizeof (on));
#ifdef ZMQ_HAVE_WINDOWS
        wsa_assert (rc != SOCKET_ERROR);
#else
        errno_assert (rc == 0);
#endif

rc = setsockopt (fd, SOL_SOCKET, SO_REUSEPORT, reinterpret_cast<char *> &on, sizeof (on));
#ifdef ZMQ_HAVE_WINDOWS
        wsa_assert (rc != SOCKET_ERROR);
#else
        errno_assert (rc == 0);
#endif
```

I'd like to submit a PR for this, but I'm uncertain if SO_REUSEPORT should be a flag set by default. Is there a chance that it would not be supported on some platforms?

# Environment

* libzmq version: 4.2.5
* OS: OSX 10.13.6

# Minimal test code / Steps to reproduce the issue

zsock_t* first = zsock_new_dish("@udp://239.0.0.1:40000");      //Works

//In another program instance
zsock_t* second = zsock_new_dish("@udp://239.0.0.1:40000");   //Address already in use error

# What's the actual result? (include assertion message & call stack if applicable)

Binding the UDP dish socket aborts with the message "Address already in use".

# What's the expected result?

Dish socket binds with a result of 0.

**Comment by bluca** [comment] 2018-08-29 10:39
Yes please send a PR. Just have an ```#ifdef SO_REUSEPORT``` for other platforms, I think that's enough.

**Comment by jamesdillonharvey** [comment] 2018-08-29 11:14
Just as a heads up (I fixed a similar issue in openpgm) on linux >=3.9
SO_REUSEPORT
limits the reuse to the same user ID I think. Also I remember something
about load balancing (basically its not the same as the old BSD SO_REUSEPORT
option).

**Comment by bluca** [comment] 2018-08-29 11:59
> Just as a heads up (I fixed a similar issue in openpgm) on linux >=3.9
SO_REUSEPORT
limits the reuse to the same user ID I think. Also I remember something
about load balancing (basically its not the same as the old BSD SO_REUSEPORT
option).

Thanks - I think that's a reasonable limitation, and down to the OS implementation, so it's probably fine if we don't worry about it too much

**Comment by jamesdillonharvey** [comment] 2018-08-29 13:08
Sure I agree about the user ID but are we ok with the load balancing on linux 3.9?  To me it sounds bad, like a radio/dish pattern that performs more like a push/pull and distributes work.

From the section on >=3.9
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

> Additionally the kernel performs some "special magic" for SO_REUSEPORT sockets that isn't found in other operating systems: For UDP sockets, it tries to distribute datagrams evenly, for TCP listening sockets, it tries to distribute incoming connect requests (those accepted by calling accept()) evenly across all the sockets that share the same address and port combination.

**Comment by bluca** [comment] 2018-08-29 13:10
Right, I didn't know about LD - thanks. That is not fine, as you guessed it would break the pattern.

**Comment by Mystfit** [comment] 2018-08-29 13:37
@jamesdillonharvey Thanks for your insight into this behaviour. Load balancing is definitely not the effect I was targeting and it would be confusing to have such a behaviour if you were expecting a copy of the UDP message to show up on each socket, which was what I was trying to achieve with multicast.

**Comment by Mystfit** [comment] 2018-08-30 02:02
@jamesdillonharvey  [I've written a small sender/receiver example using UDP multicast addresses](https://gist.github.com/Mystfit/6c015257b637ae31bcb63130da67627c) and Dish/Radio sockets and ran it on Ubuntu 18.04 in a VM using my SO_REUSEPORT addition. If I open up multiple receivers, they all receive the UDP message, I can't seem to see any evidence of one receiver getting the message over another one.

**Comment by jamesdillonharvey** [comment] 2018-08-30 09:03
Hi @Mystfit,

Yes that's correct, using mcast all the receivers will always get all the datagrams.

**Regarding unicast UDP**

I think what you are seeing is expected behaviour for SO_REUSEADDR, where one receiver gets all the datagrams and another will take over if the first dies.

The SO_REUSEPORT *should*  load balance the datagrams.

What OS/kernel version are you using?  This is a grey area, for instance the feature was only available in kernel >=3/9 but redhat backported to RHEL 6.5, which uses version 2.6.32.

**Comment by bluca** [comment] 2018-08-30 11:49
Thanks for the analysis. I think the way to go is to restrict the option only to multicast binds. Does that make sense?

**Comment by jamesdillonharvey** [comment] 2018-08-30 11:58
It makes sense to me, to be honest I can't think of a case where I would use unicast for RADIO/DISH.

**Comment by Mystfit** [comment] 2018-08-31 02:05
Makes sense. I've moved SO_REUSEPORT further down to only apply to multicast addresses.

**Comment by bluca** [comment] 2018-08-31 08:38
Fixed by https://github.com/zeromq/libzmq/pull/3237

**Closed by bluca** 2018-08-31 08:38 UTC
Labels: Area (Runtime / Usage), Transport (UDP)

**Comment by l0k18** [comment] 2020-02-22 14:53
Just want to let you know I also came across this issue but SO_REUSEPORT was not the correct flag to use, but rather SO_REUSEADDR. https://github.com/p9c/pod/commit/cd85b2dab4d9d4945294579448e8a5dcfdec7131

It's probable you haven't tested your patch on darwin or *bsd architectures, it likely does not work because SO_REUSEPORT is different in a critical way between linux/android/windows and darwin/*bsd. Of course I could be wrong about this and it be irrelevant but it was a big deal for me getting this working.
