### ISSUE TITLE
context.close() hangs

### ISSUE THREAD

**Issue by smrt28** [zeromq/libzmq#2312] opened 2017-01-19 13:21 UTC
Hi, this code hangs. Nothing is listening on tcp://localhost:21455:

```
#include <zmq.hpp>
#include <string>
#include <iostream>

int main() {
    zmq::context_t context (1);
    zmq::socket_t socket (context, ZMQ_REQ);
    int linger = 0;
    socket.connect("tcp://localhost:21455");
    socket.setsockopt(ZMQ_LINGER, &linger, sizeof (linger));
    //socket.close();
    context.close();
    return 0;
}
```
I encountered the behavior originally on ruby binding and created the related bug for it:
[ffi-rzmq](https://github.com/chuckremes/ffi-rzmq/issues/122)

I haven't fully investigated why it happen, but I suspect commit 096007c. When I close the socket before context.close() the program exits normally.

**Comment by bluca** [comment] 2017-01-19 13:33
Can you reproduce without using cppzmq? Also it's good behaviour to close sockets before contexts anyway.

**Comment by smrt28** [comment] 2017-01-19 13:49
Hmm,  not sure about the docs meaning. Is it even possible to have all the sockets within the context  closed without satisfying the second condition?

>  2. After interrupting all blocking calls, zmq_term() shall block until the following conditions are satisfied:
>       ·   All sockets open within context have been closed with zmq_close().
>       ·   For each socket within context, all messages sent by the application with zmq_send()
>  have either been physically transferred to a network peer, or the socket’s linger period set with 
> the ZMQ_LINGER socket option has expired.

**Comment by wenjians** [comment] 2017-01-20 04:13
I believe you should close socket firstly.  

as what you mentioned above, my understanding is that it is for multiple thread, with context.close, it will notify event to all pending socket that current pending wait, for those thread, they should close the socket if need. and context.close will wait until all socket is successfully closed. in your case (I assume it is single thread), it will hang since the socket is not closed.

**Comment by Asmod4n** [comment] 2017-01-21 23:05
You first might call zmq_ctx_shutdown on your context, then you must shut down all sockets created in that context and then call zmq_ctx_term.
If any socket still wants to send out messages you have to set its linger sockpot to zero.

In Ruby you can create a at_exit handler for that.

**Comment by sigiesec** [comment] 2017-09-21 08:36
As stated before, this is the expected behavior. All sockets must be closed before closing the context may complete.

**Closed by sigiesec** 2017-09-21 08:36 UTC
Labels: Area (Runtime / Usage), Symptom (Hang)

**Comment by themightyoarfish** [comment] 2024-09-18 12:48
What if one closes all the sockets and still `close()` on the context hangs? We create context as an instance variable and close it in the object's destructor after closing associated sockets, but still it hangs in `recv()`, even with `linger` set to 0 for all sockets.

**Comment by themightyoarfish** [comment] 2024-09-18 13:03
Update: I believe in my case this is because some monitoring sockets (via cppzmq `monitor_t`) exist on the context, and those cannot be trivially closed from outside the object.
