### ISSUE TITLE
Problem: memory leak seems exists in zmq

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/libzmq#2474] opened 2017-03-28 14:48 UTC
In one of my server, we use zmq 4.1.6 to transmit lots of message. And the server service lots of caller. All caller built with version across zmq2 to zmq4, but the memory of my server is crazy incr.
In the server, I use pull / push / router mode, and all socket use bind with tcp.

![image](https://cloud.githubusercontent.com/assets/7036040/24411517/ab83c100-1408-11e7-82b6-8fda8e62c68f.png)

I add keepalive as problem described here https://github.com/zeromq/libzmq/issues/1453
And also control all hwm, to limit memory use, but all action make no sense.

Well, in old version of the server, which is build by zmq2, also has this problem, but memory incr slower.

**And In another Clusters of this server, which the amount msg transmission is much less, and only service for zmq3 and zmq4. The memory use is stable.**

**Comment by bluca** [comment] 2017-03-28 14:54
Have you tried running with Valgrind? We have a Valgrind job in the CI and it's all clean

**Comment by laplaceyang** [comment] 2017-03-28 14:56
@bluca I also believe, there is no memory leak in zmq4.1.6, because we use it in many server.
But I'm not sure if there is some resource not clean where run with zmq2?

**Comment by bluca** [comment] 2017-03-28 15:02
I would suggest running with Valgrind, then you will know for sure. Can you upload the code to pastebin/gist? Or even better a minimal example that reproduces the problem
Without that data, and without seeing the code, it's just impossible to tell what's going on I'm afraid.

**Comment by laplaceyang** [comment] 2017-03-28 15:05
@bluca I will trying to write a minimal example and the valgrind those days.

**Comment by laplaceyang** [comment] 2017-04-04 09:15
@bluca I find the the cause of the problem.

In my server, I use the ROUTER mode, to send to peer of  specify identity, which use ip as identity, so I can send msg to specify peer.

And the ROUTER mode never recv msg, but always send msg.

But In zmq, there is a delay flag for pipe to delay for destroy itself. And ROUTER just delay this to next recv action.

So, pipe of my ROUTER can never be deleted.

And I fix this by add a timer in my application, to call the `getsocketopt(ZMQ_EVENTS, xx, xx)`, so as to call things like recv.

Is it necessary for us to provide a option for deciding to use delay or not?

**Comment by bluca** [comment] 2017-04-04 11:10
Perfect, glad you found the solution, thanks for reporting back. Closing since it's fixed.

**Closed by bluca** 2017-04-04 11:10 UTC

**Comment by neel-parikh** [comment] 2017-11-07 20:31
@laplaceyang 
Can you please post a snippet of how did you fix this issue. 
Appreciate your time.
Thank you.

**Comment by laplaceyang** [comment] 2017-11-09 14:01
@neel-parikh In my situation, I use ROUTER-DELEAR model and my router server only send msg but never recv msg. This situation lead to that the memory of pipe in the server never freed.
Solution: call recv in router model. And I use getsockopt(ZMQ_EVENTS) in timer, since the getsockopt(ZMQ_EVENTS) has process of prefetch the msg, and thus this action is same as call the recv, but actually not recv any msg.

So the code is just like follow:
```
class Server {
    void timeout_cb() {
        int whatever;
        size_t sz = sizeof(whatever);
        router_sock->getsocket(ZMQ_EVENTS, &whatever, &sz);
    }
    
    void init() {
         AddEvent(router_sock, ......);
         // run the timeout callback every 10 ms
         AddTimer(10, std::bind(&Server::timeout_cb, this), NULL);
    }
    
    void run() {
        // get into event loop
        Dispatch();
    }

  zmq::socket_t router_sock;
};
```

**Comment by neel-parikh** [comment] 2017-11-09 16:55
@laplaceyang Thanks a lot.
I'll give it a shot.
